In [ ]:
import pandas as pd
import numpy as np

d={'name':['kalyani','madan','akhil','ayesha'], 'subject':['telugu','english','maths','science'],'marks':[89,99,78,87]}
df=pd.DataFrame(d)
print(df)
#add grade based on marks if marks between 80 and 90 then a if >90 A+ <70 and less than 80 then b else c
if 'grade' not in df.columns:
    conditions = [
        (df['marks'] > 90),
        (df['marks'] >= 80) & (df['marks'] <= 90),
        (df['marks'] >= 70) & (df['marks'] < 80),
        (df['marks'] < 70)
    ]
    grades = ['A+', 'A', 'B', 'C']
    df['grade'] = np.select(conditions, grades, default='C') # Default to C for anything not covered by the conditions
print(df)

      name  subject  marks
0  kalyani   telugu     89
1    madan  english     99
2    akhil    maths     78
3   ayesha  science     87
      name  subject  marks grade
0  kalyani   telugu     89     A
1    madan  english     99    A+
2    akhil    maths     78     B
3   ayesha  science     87     A


In [ ]:
import numpy as np
# Simulate 100 images of 28x28 pixels
image_batch = np.random.rand(100, 28, 28)
print("--- Input Shape ---:", image_batch.shape) # (100, 28, 28)
image_batch

--- Input Shape ---: (100, 28, 28)


array([[[0.25034534, 0.5062935 , 0.76655416, ..., 0.49189457,
         0.20929758, 0.80533731],
        [0.30354109, 0.93699803, 0.18418026, ..., 0.1705149 ,
         0.33275359, 0.03608041],
        [0.04871953, 0.67800275, 0.44076487, ..., 0.17275953,
         0.94752162, 0.74771648],
        ...,
        [0.06198675, 0.24584731, 0.5194881 , ..., 0.61525163,
         0.63630218, 0.95546361],
        [0.35098445, 0.7527589 , 0.05843307, ..., 0.65474203,
         0.86695584, 0.13158028],
        [0.86790322, 0.28012588, 0.14641173, ..., 0.69453364,
         0.2116636 , 0.66132986]],

       [[0.37523689, 0.15338731, 0.04389634, ..., 0.96086629,
         0.7136342 , 0.92211176],
        [0.42748937, 0.13676416, 0.79088442, ..., 0.2621699 ,
         0.26173479, 0.44404136],
        [0.0189922 , 0.60959501, 0.11844791, ..., 0.96808195,
         0.09405973, 0.58588628],
        ...,
        [0.62268719, 0.71979058, 0.72952441, ..., 0.88301159,
         0.17594586, 0.66561586],
        [0.7

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(pd.read_csv('/content/iris.csv'))
df
print(df.shape)
# printing 100 rows with columns sepal_length,species
df.loc[0:99,['sepal_length','species']]

(150, 5)


sepal_length     species
0            5.1      setosa
1            4.9      setosa
2            4.7      setosa
3            4.6      setosa
4            5.0      setosa
..           ...         ...
95           5.7  versicolor
96           5.7  versicolor
97           6.2  versicolor
98           5.1  versicolor
99           5.7  versicolor

[100 rows x 2 columns]

In [3]:
# Part 1: The Basics - Array Creation & Attributes (Questions 1-20)
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
b=np.array((1,2,3,4,5))
b
# How do you import the NumPy library with its conventional alias?
# How do you create a 1D NumPy array from a Python list [1, 2, 3]?
# What is the fundamental object in NumPy, and what does ndarray stand for?
# How do you create a 3x3 array of all zeros?
z=np.zeros((3,3))
print(z)
# How do you create a 2x4 array of all ones, with the data type being integer?
# o=np.ones(2,4).astype(int)
# print(o)
i=np.ones((2,4),dtype=int)
print(i)
# How do you create a 1D array of numbers from 0 to 9?
od=np.arange(10)
od
# What is the difference between np.arange(10) and
ls=np.linspace(0,10,10)
ls
print(ls.dtype)

# How do you create a 4x4 identity matrix?
i=np.eye(3,3)
id=np.identity(3)
i
id
# How do you create an array filled with a specific value, for example, a 2x3 array filled with the number 7?
ful=np.full((2,3),7)
print(ful)
# How do you create an uninitialized array of shape (3, 3)? What is the main risk of using np.empty?
em=np.empty((3,3))
print(em)
# Given an array a, how do you find its shape?
np.shape(a)
# How do you find the data type of elements in an array?
print(a.dtype)
# Given an array a, how do you find the total number of elements in it?
print(a.size)
# Given an array a, how do you find the number of dimensions it has?
a.ndim
# How do you find the data type (e.g., int64, float64) of the elements in a NumPy array?
a.dtype
# How do you find the size in bytes of each element in an array?
print(a.itemsize)
print(a.size * a.itemsize)
# How do you create a NumPy array with a specific data type, like float32?
a=np.array([1,2,3,4,5,6,7,8,9],dtype=float).reshape(3,3)
a
# How can you create a copy of a NumPy array a so that changes to the new array don't affect a?
b=a.copy()
b
b[2,0]=20
print(b)
print(a)
# How do you create a NumPy array from a tuple (1, 2, 3)?
# How do you create a 2x2 array with random floating-point numbers between 0 and 1?
# r=np.random.ranf((0,1),2,2)
# r
# How do you create a 1D array of 5 random integers between 10 and 50 (exclusive of 50)?
r=np.random.randint(10,50,21).reshape(3,7)
r
# Part 2: Indexing, Slicing, and Subsetting (Questions 21-40)
# Given a 1D array a, how do you access its first element?
a[0]
# How do you access the last element of a 1D array a?
a[-1]
# How do you select elements from index 2 to 4 (inclusive) from a 1D array?
a[2:5]
# How do you select every second element from a 1D array?
a=np.arange(100)
a[::2]
# How do you reverse a 1D array using slicing?
a[::-1]
# Given a 2D array m, how do you access the element in the 2nd row and 3rd column?
# How do you select the entire first row of a 2D array m?
a=np.arange(21).reshape(3,7)
a
a[:,5]
# How do you select the entire third column of a 2D array m?
a[:,3]
# How do you select the top-left 2x2 sub-matrix from a 2D array m?
m=np.arange(16).reshape(4,4)
m
m[:2,:2]
# How do you select the last two rows and the last two columns of a 2D array m?
m[:-2,:-2]
# How do you assign the value 0 to a specific element in a 2D array, for example, at position (1, 1)?
m[1][1]=0
m
# What is the difference between a view (slice) and a copy of an array? If you modify a slice, will the original array change?


# Given a 3D array t of shape (2, 3, 4), how do you select the first 2x2 matrix from the first "sheet"?
a=np.arange(24).reshape(2,3,4)
print(a)
a[0,1,:]
# How do you select all data corresponding to the second column, across all sheets of a 3D array?
a[1, : 2]
# How can you use slicing to create a view of an array with a specific memory layout (C-style vs. Fortran-style)?
# What does the ellipsis (...) operator do in NumPy slicing?
# How do you use np.newaxis to add a new dimension to an array?
a=np.arange(10)
print(a)
a[np.newaxis,:]
# How do you select the diagonal elements of a 2D array?
d=np.diag((2,2),6)
print('d={d}',d)
# What is "fancy indexing"?
# Using fancy indexing, how do you select the 1st, 3rd, and 4th rows from a 2D array m?
# Part 3: Basic Operations and Universal Functions (ufuncs) (Questions 41-60)
# How do you perform element-wise addition between two NumPy arrays a and b of the same shape?
a=np.arange(10)
b=np.arange(10)
# Use np.where to perform element-wise division and handle division by zero
result = np.where(b != 0, a / b, 0) # Replace division by zero with 0
print(result)
# How do you multiply every element of a NumPy array a by a scalar value of 5?
# What is a "universal function" or ufunc in NumPy?
# How do you calculate the square root of every element in an array?
# How do you calculate the exponential (e^x) of every element in an array?
# What is the difference between a * b and a.dot(b) (or a @ b) for two 2D arrays?
# How do you perform a comparison (e.g., > 10) on a NumPy array? What does the result look like?
# How do you use a boolean array to select elements from another array? (Boolean indexing)

# How do you combine two boolean conditions, for example, selecting elements that are greater than 5 AND less than 10?
a=np.arange(21)
a[(a > 5) & (a < 15)]
# What is the purpose of the np.where() function? Give a simple example.
# How do you calculate trigonometric functions like sine and cosine for all elements in an array?
# How do you round all elements of a float array to the nearest integer?
# How do you sum all the elements in a NumPy array?
a=np.arange(12).reshape(3,4)
b=np.arange(13,25).reshape(3,4)
print(a)
print(b)
sum_of_elements = np.sum(a + b)
print(f"Sum of elements after element-wise addition: {sum_of_elements}")

# How do you find the minimum and maximum values in a NumPy array?
# How do you modify an array in-place, for example, by adding 5 to all its elements without creating a new array?
# What does the modulo operator (%) do on a NumPy array?
# How do you get the integer and fractional parts of a float array separately?
a=np.arange(12).reshape(3,4) # Corrected assignment to avoid TypeError later
print(a.astype(int))
print(a.astype(float))

# How do you check if any element in a boolean array is True?
import numpy as np
a=np.array([True,False,True,False])
np.any(a)
np.all(a)
# How do you check if all elements in a boolean array is True?
np.all(a)
# How do you compute the element-wise maximum between two arrays a and b?
a=np.arange(10) # Re-initializing a and b for this section
b=np.arange(10)
np.maximum(a,b)
# How do you compute the element-wise minimum between two arrays a and b?
np.minimum(a,b)
# Part 4: Aggregations and Axis-based Operations (Questions 61-75)
# What does the axis parameter signify in NumPy functions like sum() and mean()?
a=np.arange(12).reshape(3,4)
print(a)
np.sum(a,axis=0)
np.sum(a,axis=1)
# How do you calculate the sum of all elements in an array?
np.sum(a)
# How do you calculate the mean of all elements in an array?
np.mean(a)
# How do you calculate the standard deviation of all elements in an array?
np.std(a)
# # For a 2D array, which axis corresponds to operations on columns, and which to rows?
# axis=0(column)
# axis=1(row)
# Given a 2D array m, how do you compute the sum of each column?
m=np.arange(16).reshape(4,4) # Re-initializing m
np.sum(m, axis=0)
# Given a 2D array m, how do you compute the mean of each row?
np.mean(m, axis=1)
# How do you find the index of the maximum value in a 1D array?
a=np.arange(10) # Re-initializing a
np.argmax(a)
# How do you find the indices of the minimum values for each column in a 2D array?
a=np.arange(12).reshape(3,4) # Re-initializing a
np.argmin(a,axis=0)
# How do you find the indices of the minimum values for each row in a 2D array?
np.argmin(a,axis=1)
# What is the purpose of the keepdims=True argument in aggregation functions?

# How do you calculate the cumulative sum of elements in a 1D array?
a=np.arange(10) # Re-initializing a
np.cumsum(a)
# How do you calculate the cumulative product of elements along the rows of a 2D array?
a=np.arange(12).reshape(3,4) # Re-initializing a
np.cumprod(a, axis=1)
# How do you compute the standard deviation of an entire 2D array?
np.std(a)
# How do you compute the variance for each row of a 2D array?
np.var(a, axis=1)
# How do you count the number of non-zero elements in an array?
a=np.array([0, 1, 0, 2, 0, 3]) # Re-initializing a
np.count_nonzero(a)
# How do you find the difference between the maximum and minimum value in an array (also known as the peak-to-peak value)?
a=np.arange(10) # Re-initializing a
np.ptp(a)
# Given a 3D array, what would arr.sum(axis=(0, 2)) calculate?
a=np.arange(24).reshape(2,3,4)
print(a)
np.sum(a,axis=(0,2))
# How can you find the 75th percentile for each column of a 2D array?
a=np.arange(12).reshape(3,4) # Re-initializing a
np.percentile(a,75, axis=0)
# How do you sort a 1D array in ascending order?
a=np.array([3, 1, 2]) # Re-initializing a
np.sort(a)
# Part 5: Array Manipulation (Questions 76-100)
# How do you change the shape of an array from (2, 6) to (3, 4)? What is the one condition that must be met?
a=np.arange(12).reshape(2,6)
a
a.reshape(3,4)
# What does the -1 signify when used in a reshape() operation?
# What is the difference between ravel() and flatten()?

# How do you transpose a 2D array m?
m=np.arange(6).reshape(2,3) # Re-initializing m
m.T
# How do you join a sequence of arrays together vertically?
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.vstack((a1, a2))
# How do you join a sequence of arrays together horizontally?
np.hstack((a1, a2))
# What is the more general function for joining arrays, and how would you use it to replicate vstack?
# np.concatenate
np.concatenate((a1[:, np.newaxis], a2[:, np.newaxis]), axis=1) # replicating hstack
np.concatenate((a1[np.newaxis, :], a2[np.newaxis, :]), axis=0) # replicating vstack
# How do you split an array into 3 equal-sized sub-arrays?
a=np.arange(9) # Re-initializing a
np.split(a, 3)
# How do you split an array horizontally at the 2nd and 4th columns?
a=np.arange(12).reshape(3,4) # Re-initializing a
np.hsplit(a, [2, 4])
# How do you repeat each element of a 1D array 3 times?
a=np.array([1, 2, 3]) # Re-initializing a
np.repeat(a, 3)
# What is the difference between np.repeat() and np.tile()?
# How do you add a new row of data to the end of an existing 2D array?
a=np.arange(6).reshape(2,3) # Re-initializing a
new_row = np.array([6, 7, 8])
np.vstack((a, new_row))
# How do you insert a new column of zeros into a 2D array at the second position?
a=np.arange(6).reshape(2,3) # Re-initializing a
new_column = np.zeros((a.shape[0], 1))
np.insert(a, 1, new_column, axis=1)
# How do you delete the 3rd row from a 2D array?
a=np.arange(9).reshape(3,3) # Re-initializing a
np.delete(a, 2, axis=0)
# How do you find the unique elements in a NumPy array?
a=np.array([1, 1, 2, 3, 3, 4]) # Re-initializing a
np.unique(a)
# How can you also get the counts of the unique elements?
np.unique(a, return_counts=True)
# How do you reverse the order of rows in a 2D array?
a=np.arange(6).reshape(2,3) # Re-initializing a
a[::-1, :]
# How do you sort the elements of a 1D array?
a=np.array([3, 1, 2]) # Re-initializing a
np.sort(a)
# What is the difference between np.sort(a) and a.sort()?
# How do you sort a 2D array based on the values in its second column?
a=np.array([[1, 5], [3, 2], [2, 4]]) # Re-initializing a
a[a[:, 1].argsort()]
# What does np.argsort() return?
# How do you remove all dimensions of size 1 from an array using squeeze()?
a=np.zeros((1, 2, 1, 3)) # Re-initializing a
np.squeeze(a)
# How do you add a dimension of size 1 using expand_dims()?
a=np.array([1, 2, 3]) # Re-initializing a
np.expand_dims(a, axis=0)
# How can you swap two axes of an array, for example, axis 0 and axis 2 in a 3D array?
a=np.arange(24).reshape(2,3,4) # Re-initializing a
np.swapaxes(a, 0, 2)
# How do you create a 2D array where the border is 1s and the inside is 0s?
a=np.zeros((5,5)) # Re-initializing a
a[1:-1, 1:-1] = 1
a
# Part 6: Broadcasting, Random Sampling, and Statistics (Questions 101-125)
# What is broadcasting in NumPy?
# Give a simple example of broadcasting a scalar to an array.
# Can you add a 1D array of shape (3,) to a 2D array of shape (4, 3)? Explain why or why not.

# How would you reshape a 1D array of shape (4,) so it can be broadcasted and added to a (4, 3) array?
# What are the formal rules of broadcasting?
# How do you set the random seed in NumPy to make your random operations reproducible?
# How do you generate a random sample from a standard normal distribution (mean=0, variance=1)?
# How do you generate a 5x5 array of random numbers from a uniform distribution over [0, 10)?
# How do you randomly shuffle the elements of a 1D array in-place?
# How do you get a random permutation of an array without modifying the original array?
# How do you randomly pick 3 elements from a 1D array without replacement?
# How do you generate random numbers that follow a specific probability distribution (e.g., binomial, Poisson)?
# What is the purpose of the np.random.default_rng() object?
# How do you calculate the average of an array, ignoring NaN values?
# How do you compute the correlation coefficient matrix for a 2D array where each row is an observation and each column is a feature?
# How do you compute the covariance between two 1D arrays?
# How do you create a histogram of a 1D array of data, binning the values into 10 equal bins?

# What does np.digitize() do?
# How do you find the indices that would sort an array?
# How do you calculate the weighted average of a 1D array, given another array of weights?
# How can you clip the values of an array to be within a specific range (e.g., between 0 and 1)?
# How do you check for the presence of NaN or Inf in a NumPy array?
# How do you replace all NaN values in an array with 0?
# How do you find the unique rows in a 2D array?
# How do you get the sign of every element in an array (-1 for negative, 0 for zero, 1 for positive)?
# Part 7: Advanced Topics - Linear Algebra, I/O, and Performance (Questions 126-150)
# How do you compute the dot product of two 1D vectors?
# How do you compute the inverse of a square matrix?
# How do you compute the determinant of a matrix?
# How do you solve a system of linear equations of the form Ax = b?
# How do you compute the eigenvalues and eigenvectors of a square matrix?
# How do you compute the trace of a matrix (the sum of the diagonal elements)?
# How do you perform a Singular Value Decomposition (SVD) on a matrix?
# How do you save a NumPy array to a binary file (.npy)?
# How do you load a NumPy array from a .npy file?
# How do you save multiple NumPy arrays into a single compressed .npz file?
# How do you load a single array by name from an .npz file?
# How do you save a 2D array to a text file with comma-separated values?
# How do you load data from a CSV file into a NumPy array, skipping the header row?
# What is a structured array? How do you define one with fields for 'name' (string), 'age' (int), and 'height' (float)?
# How do you access the data of a single field (e.g., 'age') from a structured array?
# Why are NumPy operations generally faster than equivalent operations on Python lists?
# What is vectorization?
# What is the purpose of the np.vectorize function? Is it primarily for performance or convenience?
# What does the np.einsum function do? Provide an example for calculating the trace of a matrix.
# How do you find the memory layout of an array (C-contiguous vs. F-contiguous)?
# How do you fit a polynomial of degree 2 to a set of data points x and y?
# How do you create a view of an array with a different data type without copying the data?
# What is the Global Interpreter Lock (GIL) and how does NumPy get around it to achieve parallelism?
# How do you calculate the outer product of two 1D vectors?
# How do you find the set difference between two 1D arrays (elements in the first array but not in the second)?

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
float64
[[7 7 7]
 [7 7 7]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
int64
5
8
40
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [20.  8.  9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[0 1 2 3 4 5 6 7 8 9]
d={d} [[0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Sum of elements after element-wise addition: 288
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


/tmp/ipython-input-1971898343.py:119: RuntimeWarning: invalid value encountered in divide
  result = np.where(b != 0, a / b, 0) # Replace division by zero with 0


array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

**Question: What are the formal rules of broadcasting?**

**Chain of Thought:**
1.  The user wants to know the formal rules that govern NumPy broadcasting.
2.  These rules determine if two arrays are compatible for element-wise operations and how the smaller array is "stretched" to match the shape of the larger array.
3.  The rules are applied by comparing the shapes of the two arrays dimension by dimension, starting from the trailing dimension (the last one).
4.  For each dimension being compared, one of the following conditions must be met:
    *   The dimensions are equal.
    *   One of the dimensions is 1.
    *   One of the dimensions is missing (this applies when comparing an array with fewer dimensions to an array with more dimensions; the shape of the smaller array is effectively padded with ones on its left).
5.  If these conditions are met for all dimensions, the arrays are broadcastable.
6.  The size of the resulting output array's dimension is the maximum of the sizes of the input arrays' dimensions along that axis. If one dimension was 1, the other dimension's size is used. If one dimension was missing, the other dimension's size is used.

**Answer:** The formal rules of broadcasting in NumPy are:

1.  **Compare Dimensions:** Compare the shapes of the two arrays dimension by dimension, starting with the trailing dimensions.
2.  **Check Compatibility:** For each dimension, the sizes must be either equal, or one of them must be 1.
3.  **Prepend Ones:** If the arrays have different numbers of dimensions, the shape of the array with fewer dimensions is padded with ones on its left side until the shapes have the same length.
4.  **Determine Output Shape:** The size of the output array's dimension at each position is the maximum of the sizes of the input arrays' dimensions at that position.

If the comparison fails for any dimension (i.e., the sizes are not equal and neither is 1), a `ValueError` is raised, indicating that the arrays are not broadcastable.

In [6]:
# Example to illustrate reshaping a (4,) array to (4, 1) for column-wise addition
import numpy as np

array_2d = np.arange(12).reshape(4, 3)
array_1d_shape4 = np.array([10, 20, 30, 40]) # Original shape (4,)

# Reshape to (4, 1)
array_1d_reshaped = array_1d_shape4.reshape(4, 1)
# Alternatively: array_1d_reshaped = array_1d_shape4[:, np.newaxis]

print("2D array (shape:", array_2d.shape, "):")
print(array_2d)

print("\n1D array reshaped to (4, 1) (shape:", array_1d_reshaped.shape, "):")
print(array_1d_reshaped)

print("\nResult of adding (4, 3) and reshaped (4, 1) arrays (column-wise addition):")
# The (4, 1) array is broadcast to (4, 3) by repeating its elements across the columns
result_add_reshaped = array_2d + array_1d_reshaped
print(result_add_reshaped)
print("Result shape:", result_add_reshaped.shape)

2D array (shape: (4, 3) ):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

1D array reshaped to (4, 1) (shape: (4, 1) ):
[[10]
 [20]
 [30]
 [40]]

Result of adding (4, 3) and reshaped (4, 1) arrays (column-wise addition):
[[10 11 12]
 [23 24 25]
 [36 37 38]
 [49 50 51]]
Result shape: (4, 3)


Now, let's illustrate reshaping the (4,) array to (4, 1) if you wanted to add it *column-wise*.

**Chain of Thought (Reshaping for column-wise addition):**
1.  The user might be thinking about adding a 1D array such that its elements are added to corresponding columns of the 2D array.
2.  If the 1D array has shape (4,), to broadcast it across the columns of a (4, 3) array, its shape needs to be compatible dimension-wise.
3.  Comparing (4, 3) and (4,) again: the trailing dimensions (3 and 1 implicitly) match, but the next dimensions (4 and 4) also match. This leads to the row-wise broadcasting shown above.
4.  To achieve column-wise addition, the 1D array needs to have a shape where its length matches the number of rows in the 2D array (4) and has a dimension of size 1 that can be broadcast across the columns (3).
5.  Reshaping the (4,) array to (4, 1) achieves this.
6.  Comparing shapes (4, 3) and (4, 1):
    *   Trailing dimension: 3 and 1. One is 1, so they match.
    *   Next dimension: 4 and 4. These are equal, so they match.
7.  This shape (4, 1) is compatible for broadcasting with (4, 3), and the broadcasting will occur along the dimension of size 1 in the (4, 1) array (axis 1), effectively adding the elements column-wise.

**Answer (Reshaping for column-wise addition):** To specifically reshape a 1D array of shape (4,) so its elements are added column-wise to a (4, 3) array, you would reshape it to (4, 1). You can do this using `.reshape(4, 1)` or by adding a new axis using `array_1d_shape4[:, np.newaxis]`.

In [5]:
# Example to illustrate adding a (4,) array to a (4, 3) array (direct broadcasting)
import numpy as np

array_2d = np.arange(12).reshape(4, 3)
array_1d_shape4 = np.array([10, 20, 30, 40]) # Shape (4,)

print("2D array (shape:", array_2d.shape, "):")
print(array_2d)

print("\n1D array (shape:", array_1d_shape4.shape, "):")
print(array_1d_shape4)

print("\nResult of adding (4, 3) and (4,) arrays (direct broadcasting):")
# The (4,) array is broadcast to (4, 3) by repeating each element across the columns
result_add_broadcast = array_2d + array_1d_shape4
print(result_add_broadcast)
print("Result shape:", result_add_broadcast.shape)

2D array (shape: (4, 3) ):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

1D array (shape: (4,) ):
[10 20 30 40]

Result of adding (4, 3) and (4,) arrays (direct broadcasting):


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

**Question: How would you reshape a 1D array of shape (4,) so it can be broadcasted and added to a (4, 3) array?**

**Chain of Thought:**
1.  The user wants to add a 1D array of shape (4,) to a 2D array of shape (4, 3).
2.  Let's compare the shapes (4, 3) and (4,) using broadcasting rules:
    *   Trailing dimension: 3 and (missing). The missing dimension is treated as 1. So we compare 3 and 1. These are not equal, but one is 1, so they match.
    *   Next dimension: 4 and 4. These are equal, so they match.
3.  Broadcasting is possible in this case without reshaping the (4,) array. The (4,) array will be broadcast along axis 1 (columns) to match the shape (4, 3). Each element in the (4,) array will be broadcast across the 3 columns of the corresponding row in the (4, 3) array.

**Answer:** You don't need to reshape a 1D array of shape (4,) to broadcast it and add it to a (4, 3) array. NumPy's broadcasting rules allow this directly. The (4,) array will be broadcast along the columns (axis 1).

However, if you *wanted* to reshape a (4,) array to be added column-wise to a (4, 3) array (meaning each element of the (4,) array is added to a *column* of the (4, 3) array), you would need to reshape the (4,) array to (4, 1).

Let's illustrate the direct broadcasting first, as it answers the literal question. Then I'll show the (4, 1) reshape for clarity on how reshaping can influence broadcasting.

In [4]:
# Example to illustrate adding a (3,) array to a (4, 3) array
import numpy as np

array_2d = np.arange(12).reshape(4, 3)
array_1d = np.array([1, 2, 3])

print("2D array (shape:", array_2d.shape, "):")
print(array_2d)

print("\n1D array (shape:", array_1d.shape, "):")
print(array_1d)

print("\nResult of adding 2D and 1D arrays (broadcasted):")
# The 1D array is broadcast to (4, 3) by repeating its elements across the rows
result_add = array_2d + array_1d
print(result_add)
print("Result shape:", result_add.shape)

2D array (shape: (4, 3) ):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

1D array (shape: (3,) ):
[1 2 3]

Result of adding 2D and 1D arrays (broadcasted):
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
Result shape: (4, 3)


**Step 1: Explain Broadcasting**

Let's address your questions about broadcasting.

**Question: Can you add a 1D array of shape (3,) to a 2D array of shape (4, 3)? Explain why or why not.**

**Chain of Thought:**
1.  The user is asking about adding two NumPy arrays with different shapes: a 1D array of shape (3,) and a 2D array of shape (4, 3).
2.  NumPy's broadcasting rules determine if and how arrays with different shapes can be combined in element-wise operations.
3.  The broadcasting rules compare the shapes of the arrays dimension by dimension, starting from the trailing dimension.
4.  For broadcasting to be possible, the dimensions being compared must either be equal, or one of them must be 1 (or missing).
5.  Let's compare the shapes (4, 3) and (3,).
    *   Trailing dimension: 3 and 3. These are equal, so they match.
    *   Next dimension: 4 and (missing). The missing dimension is treated as 1. So we compare 4 and 1. These are not equal, but one is 1, so they match.
6.  Since all dimensions match according to the broadcasting rules, the 1D array of shape (3,) can be broadcast to the shape (4, 3).
7.  The 1D array (3,) will be "stretched" or duplicated across the missing dimension (axis 0) four times to match the shape (4, 3).

**Answer:** Yes, you can add a 1D array of shape (3,) to a 2D array of shape (4, 3) due to NumPy's broadcasting rules. The 1D array will be broadcast across the rows of the 2D array.

In [ ]:
import numpy as np

r = np.random.randint(10, 50, 21).reshape(3, 7)
print(r)

[[44 42 25 13 33 27 16]
 [42 26 14 12 29 31 33]
 [26 27 33 29 31 10 15]]


The ellipsis (`...`) operator in NumPy slicing is used as a shorthand to represent "as many colons as needed to produce a complete selection". It's particularly useful for high-dimensional arrays where you want to select elements along some axes without explicitly writing out all the slicing for the other axes.

For example:

- For a 3D array `arr_3d` of shape (a, b, c), `arr_3d[..., 2]` is equivalent to `arr_3d[:, :, 2]`. It selects all elements in the third column across all rows and all "sheets".
- For a 4D array `arr_4d` of shape (a, b, c, d), `arr_4d[1, ..., 3]` is equivalent to `arr_4d[1, :, :, 3]`. It selects elements from the second item along the first axis and the fourth item along the last axis, across all elements in the middle two axes.

In essence, the ellipsis fills in the missing dimensions with full slices (`:`) to make the slicing operation complete.

In [ ]:
import numpy as np

# Create a 2x3 array of random integers between 20 and 30
random_array_2x3 = np.random.randint((20, 30), size=(2, 3))


print(random_array_2x3)

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 1 with shape (2,) and arg 2 with shape (2, 3).

In [ ]:
import numpy as np

# Create a 1D array of 10 random integers between 20 and 30
random_integers = np.random.randint(20, 30, 10)

print(random_integers)

[27 29 21 28 27 28 23 28 21 22]


In [ ]:
import numpy as np

# Create a 2x2 array of random floats between 0 and 1
random_array = np.random.rand(2, 2)

print(random_array)

[[0.76593949 0.91984189]
 [0.93307707 0.47256444]]


In [ ]:
em=np.empty((4,3))
print(em)
print(em.sum())

[[3.90497650e-315 0.00000000e+000 2.10077583e-312]
 [6.79038654e-313 2.22809558e-312 2.14321575e-312]
 [2.35541533e-312 6.79038654e-313 2.22809558e-312]
 [2.14321575e-312 2.46151512e-312 2.41907520e-312]]
1.9441386426684e-311


In [108]:
import numpy as np

# Create a 5x5 identity matrix (diagonal with ones)
identity_matrix = np.eye(5)
print("Identity Matrix:")
print(identity_matrix)

# Create a 5x5 matrix with a specific value on the diagonal
diagonal_matrix_value = np.diag([1, 2, 3, 4, 5])
print("\nDiagonal Matrix with a list of values:")
print(diagonal_matrix_value)

# Create a rectangular matrix with a diagonal offset
# A 4x6 matrix with the diagonal starting at the first column (k=0)
diag_offset_0 = np.diag(np.arange(4), k=0)
print("\nDiagonal with offset k=0 (square):")
print(diag_offset_0)

# A 4x6 matrix with the diagonal starting one column to the right (k=1)
diag_offset_1 = np.diag(np.arange(4), k=1)
print("\nDiagonal with offset k=1 (rectangular):")
print(diag_offset_1)

# A 6x4 matrix with the diagonal starting one row down (k=-1)
diag_offset_neg_1 = np.diag(np.arange(3), k=-1)
print("\nDiagonal with offset k=-1 (rectangular):")
print(diag_offset_neg_1)

# Create a square matrix from a 1D array, placing the elements on the diagonal
arr_1d = np.array([10, 20, 30, 40])
square_diag_from_1d = np.diag(arr_1d)
print("\nSquare matrix from 1D array on diagonal:")
print(square_diag_from_1d)

# Extract the diagonal from an existing square matrix
existing_matrix = np.arange(16).reshape(4, 4)
diagonal_elements = np.diag(existing_matrix)
print("\nExisting matrix:")
print(existing_matrix)
print("Extracted diagonal elements:")
print(diagonal_elements)

# Extract an off-diagonal
off_diagonal_elements = np.diag(existing_matrix, k=1)
print("\nExtracted off-diagonal (k=1):")
print(off_diagonal_elements)

# Extract an off-diagonal below the main diagonal
off_diagonal_elements_neg = np.diag(existing_matrix, k=-1)
print("\nExtracted off-diagonal (k=-1):")
print(off_diagonal_elements_neg)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Matrix with a list of values:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Diagonal with offset k=0 (square):
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]

Diagonal with offset k=1 (rectangular):
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]]

Diagonal with offset k=-1 (rectangular):
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]]

Square matrix from 1D array on diagonal:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]

Existing matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted diagonal elements:
[ 0  5 10 15]

Extracted off-diagonal (k=1):
[ 1  6 11]

Extracted off-diagonal (k=-1):
[ 4  9 14]


In [ ]:
import numpy as np
r=np.random.rand(2,2)
r

array([[0.00464057, 0.75719069],
       [0.18797117, 0.16807462]])

In [82]:
import numpy as np

# Create a 3D array of shape (3, 4, 5)
arr_3d = np.arange(60).reshape(3, 4, 5)
print("Original 3D array:")
print(arr_3d)
print("\n--- Slicing Use Cases ---")

# 1. Select the first "sheet" (axis 0)
print("\n1. First sheet:")
print(arr_3d[0, :, :])

# 2. Select the second row of the first sheet
print("\n2. Second row of the first sheet:")
print(arr_3d[0, 1, :])

# 3. Select the third column of the second sheet
print("\n3. Third column of the second sheet:")
print(arr_3d[1, :, 2])

# 4. Select a 2x3 sub-array from the first sheet
print("\n4. 2x3 sub-array from the first sheet:")
print(arr_3d[0, 0:2, 0:3])

# 5. Select all sheets, the first two rows, and the last three columns
print("\n5. All sheets, first two rows, last three columns:")
print(arr_3d[:, 0:2, -3:])

# 6. Select every other row from the first sheet
print("\n6. Every other row from the first sheet:")
print(arr_3d[0, ::2, :])

# 7. Select every third element from the first row of the second sheet
print("\n7. Every third element from the first row of the second sheet:")
print(arr_3d[1, 0, ::3])

# 8. Reverse the order of rows in the first sheet
print("\n8. Reversed rows in the first sheet:")
print(arr_3d[0, ::-1, :])

# 9. Reverse the order of columns in all sheets
print("\n9. Reversed columns in all sheets:")
print(arr_3d[:, :, ::-1])

# 10. Select a single element at index (1, 2, 3)
print("\n10. Single element at (1, 2, 3):")
print(arr_3d[1, 2, 3])

# 11. Select a range of elements along the first axis
print("\n11. Range along the first axis (sheets 0 and 1):")
print(arr_3d[0:2, :, :])

# 12. Select specific rows [0, 2] from all sheets and columns (fancy indexing)
print("\n12. Specific rows [0, 2] from all sheets and columns:")
print(arr_3d[:, [0, 2], :])

# 13. Select specific columns [1, 4] from all sheets and rows (fancy indexing)
print("\n13. Specific columns [1, 4] from all sheets and rows:")
print(arr_3d[:, :, [1, 4]])

# 14. Select elements using a boolean mask (example: elements > 30)
print("\n14. Elements greater than 30 (boolean indexing):")
print(arr_3d[arr_3d > 30])

# 15. Select a sub-array using a combination of slicing and fancy indexing
print("\n15. Sub-array using slicing and fancy indexing (first sheet, rows 1 and 3, all columns):")
print(arr_3d[0, [1, 3], :])

# 16. Using ellipsis to select all elements along certain axes
print("\n16. Using ellipsis to select all elements in the third column of all sheets and rows:")
print(arr_3d[..., 2])

# 17. Select the first element of each sheet
print("\n17. First element of each sheet:")
print(arr_3d[:, 0, 0])

# 18. Select the last element of each sheet
print("\n18. Last element of each sheet:")
print(arr_3d[:, -1, -1])

# 19. Select a 1D array by fixing two axes
print("\n19. 1D array by fixing two axes (second sheet, third row):")
print(arr_3d[1, 2, :])

# 20. Select a 2D array by fixing one axis
print("\n20. 2D array by fixing one axis (second sheet):")
print(arr_3d[1, :, :])

Original 3D array:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

--- Slicing Use Cases ---

1. First sheet:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

2. Second row of the first sheet:
[5 6 7 8 9]

3. Third column of the second sheet:
[22 27 32 37]

4. 2x3 sub-array from the first sheet:
[[0 1 2]
 [5 6 7]]

5. All sheets, first two rows, last three columns:
[[[ 2  3  4]
  [ 7  8  9]]

 [[22 23 24]
  [27 28 29]]

 [[42 43 44]
  [47 48 49]]]

6. Every other row from the first sheet:
[[ 0  1  2  3  4]
 [10 11 12 13 14]]

7. Every third element from the first row of the second sheet:
[20 23]

8. Reversed rows in the first sheet:
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]

9. Reversed columns in all sheets:
[[[ 4  3  2  1  0]
  [ 9  8  7  6  5]


In [101]:
a=np.arange(30).reshape(2,5,3)
a
print(a)
print(a[0,0,:])
print(a[0,1,:])
for i in range(5):
  print(f'row{i}',a[0,i,:])
for j in range(3):
  print(f'column{j}',a[0,:,j])
a[0,:3,:4]
a[1,2,0]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[0 1 2]
[3 4 5]
row0 [0 1 2]
row1 [3 4 5]
row2 [6 7 8]
row3 [ 9 10 11]
row4 [12 13 14]
column0 [ 0  3  6  9 12]
column1 [ 1  4  7 10 13]
column2 [ 2  5  8 11 14]


np.int64(21)

In [36]:
# Example 75: Generate samples from a standard T distribution using Generator.standard_t()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 75: Samples from standard T distribution (df=10) using Generator.standard_t():\n", rng.standard_t(10, size=5))


Example 75: Samples from standard T distribution (df=10) using Generator.standard_t():
 [ 0.4100402   0.94546385 -0.02149125  0.79294169  0.59901342]


In [40]:
# Example 70: Generate samples from a Beta distribution using Generator.beta()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 70: Samples from Beta distribution (a=0.5, b=0.5) using Generator.beta():\n", rng.beta(0.5, 0.5, size=5))

# Example 71: Generate samples from a Logistic distribution using Generator.logistic()
print("\nExample 71: Samples from Logistic distribution (loc=0, scale=1) using Generator.logistic():\n", rng.logistic(size=5))

# Example 72: Generate samples from a Gamma distribution using Generator.gamma()
print("\nExample 72: Samples from Gamma distribution (shape=2.0, scale=1.0) using Generator.gamma():\n", rng.gamma(2.0, size=5))

# Example 73: Generate samples from an Exponential distribution using Generator.exponential()
print("\nExample 73: Samples from Exponential distribution (scale=1.0) using Generator.exponential():\n", rng.exponential(size=5))

# # Example 74: Generate samples from a Chi-square distribution using Generator.chisquare()
# print("\nExample 74: Samples from Chi-square distribution (df=2) using Generator.chisquare(2, size=5))


Example 70: Samples from Beta distribution (a=0.5, b=0.5) using Generator.beta():
 [0.75668409 0.00923212 0.0748566  0.13799008 0.79199722]

Example 71: Samples from Logistic distribution (loc=0, scale=1) using Generator.logistic():
 [ 0.21921279 -2.68578707  1.56893108  0.53936376  1.14222403]

Example 72: Samples from Gamma distribution (shape=2.0, scale=1.0) using Generator.gamma():
 [0.93308771 1.47502389 1.25214422 2.18436953 2.28701715]

Example 73: Samples from Exponential distribution (scale=1.0) using Generator.exponential():
 [1.26420686 0.70849063 0.23792995 0.46108834 0.64155674]


**Step 8: Finish task**

We have now covered a wide range of functionalities within the `numpy.random` module, including setting seeds, generating random numbers from various continuous and discrete distributions using both older functions and the newer `Generator` class, performing permutations and shuffling, and looking at practical examples.

We have generated numerous examples throughout this explanation.

Do you have any further questions about the `numpy.random` module, or would you like to explore other topics in NumPy?

In [65]:
# Example 118: Recap of creating and using a Generator
import numpy as np

# Create a Generator with a seed
rng = np.random.default_rng(seed=500)

# Generate numbers from different distributions using the Generator's methods
uniform_numbers = rng.random(4)
normal_numbers = rng.normal(size=4)
integers = rng.integers(0, 10, size=4)

print("\nExample 118: Recap of Generator usage")
print("Uniform numbers:", uniform_numbers)
print("Normal numbers:", normal_numbers)
print("Integers:", integers)


Example 118: Recap of Generator usage
Uniform numbers: [0.56674314 0.85397799 0.6453572  0.41115681]
Normal numbers: [ 1.94318467 -1.38536164 -1.1492876   0.36496557]
Integers: [7 4 1 2]


**Step 7: Summarize and Recommend**

We've explored the `numpy.random` module, covering both the older module-level functions and the newer `Generator` class.

- **Older Functions (`np.random.rand`, `np.random.randint`, etc.):** Convenient for quick, simple random number generation but use a global state, which can make managing reproducibility in complex code harder.
- **Newer `Generator` Class (`np.random.default_rng()`):** The recommended approach for modern NumPy. Provides independent random states per `Generator` object, better statistical properties, and more flexibility. Its methods (`rng.random`, `rng.integers`, etc.) are the equivalents of the older functions.

For new code, it is highly recommended to use `np.random.default_rng()` to create a `Generator` object and then use its methods. This provides better control over reproducibility and is part of NumPy's future direction for random number generation.

**Example 118:** Recap of creating and using a `Generator`.

In [64]:
# Example 117: Simulating random walks
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(seed=42)

# Simulate a 1D random walk of 1000 steps
# Each step is either +1 or -1 with equal probability
steps = rng.choice([-1, 1], size=1000)

# Calculate the position at each step (cumulative sum of steps)
positions = np.cumsum(steps)

# Add the starting position (0)
positions = np.insert(positions, 0, 0)

print("\nExample 117: Simulating a 1D random walk")
print("First 10 steps:", steps[:10])
print("First 10 positions:", positions[:10])
print("Final position:", positions[-1])

# You could then plot the random walk:
# plt.plot(positions)
# plt.title("1D Random Walk")
# plt.xlabel("Step")
# plt.ylabel("Position")
# plt.show()


Example 117: Simulating a 1D random walk
First 10 steps: [-1  1  1 -1 -1  1 -1  1 -1 -1]
First 10 positions: [ 0 -1  0  1  0 -1  0 -1  0 -1]
Final position: 18


In [63]:
# Example 116: Generating random data points for plotting (e.g., scatter plot)
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(seed=42)

# Generate 50 random x and y coordinates from a normal distribution
x_data = rng.normal(loc=0, scale=1, size=50)
y_data = rng.normal(loc=5, scale=2, size=50)

print("\nExample 116: Generating random data points for plotting")
print("First 5 x data points:", x_data[:5])
print("First 5 y data points:", y_data[:5])

# You could then plot these points:
# plt.scatter(x_data, y_data)
# plt.title("Random Data Points")
# plt.xlabel("X")
# plt.ylabel("Y")
# plt.show()


Example 116: Generating random data points for plotting
First 5 x data points: [ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]
First 5 y data points: [5.5782388  6.26257645 2.08568836 4.36065757 4.05925469]


In [62]:
# Example 115: Creating a random sample for training and testing data
import numpy as np

# Assume you have a dataset with 100 samples
dataset_indices = np.arange(100)

rng = np.random.default_rng(seed=42)

# Randomly shuffle the indices
shuffled_indices = rng.permutation(dataset_indices)

# Split into training (80%) and testing (20%) indices
train_size = int(0.8 * len(dataset_indices))
train_indices = shuffled_indices[:train_size]
test_indices = shuffled_indices[train_size:]

print("\nExample 115: Random sample for training and testing data")
print("Original indices:", dataset_indices)
print("Shuffled indices:", shuffled_indices)
print("Training indices (first 80):", train_indices)
print("Testing indices (last 20):", test_indices)


Example 115: Random sample for training and testing data
Original indices: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Shuffled indices: [59 21 56 18 33 42 50 27 92 71  2 25 24 52 81 99 51 61  4 97 94 37 28 80
  7 57 79 26 76 78 38  0 86 46 10 29 70 45 17 39 91 40 89  5 68  1 95 84
 63  3 83 93 20 87 43 73 32 75 23 96 69 15 48 55 60  9 62 31 72 16 44 82
 67 34 30 58 74 88 98 54 49  6 90 11 85 41 22 19 35 64 47 12 53 14 13 66
 36 65 77  8]
Training indices (first 80): [59 21 56 18 33 42 50 27 92 71  2 25 24 52 81 99 51 61  4 97 94 37 28 80
  7 57 79 26 76 78 38  0 86 46 10 29 70 45 17 39 91 40 89  5 68  1 95 84
 63  3 83 93 20 87 43 73 32 75 23 96 69 15 48 55 60  9 62 31 72 16 44 82
 67 34 30 58 74 88 98 54]
Testing indices (las

In [61]:
# Example 114: Simulating rolling a standard six-sided die
import numpy as np

rng = np.random.default_rng(seed=42)
# Simulate a single die roll (integers from 1 to 6 inclusive)
die_roll_result = rng.integers(1, 7, endpoint=True)
print("\nExample 114: Standard six-sided die roll:", die_roll_result)

# Simulate 5 die rolls
five_die_rolls = rng.integers(1, 7, endpoint=True, size=5)
print("Simulating 5 die rolls:", five_die_rolls)


Example 114: Standard six-sided die roll: 1
Simulating 5 die rolls: [6 5 4 4 7]


In [60]:
# Example 113: Simulating a fair coin toss
import numpy as np

rng = np.random.default_rng(seed=42)
# 0 for tails, 1 for heads
coin_toss_result = rng.choice([0, 1])
print("\nExample 113: Fair coin toss result (0=Tails, 1=Heads):", coin_toss_result)

# Simulate 10 coin tosses
ten_coin_tosses = rng.choice([0, 1], size=10)
print("Simulating 10 coin tosses:", ten_coin_tosses)


Example 113: Fair coin toss result (0=Tails, 1=Heads): 0
Simulating 10 coin tosses: [1 1 0 0 1 0 1 0 0 1]


**Step 6: Provide Practical Examples**

Let's illustrate how `np.random` can be used in some common practical scenarios.

**Example 113:** Simulating a fair coin toss.
**Example 114:** Simulating rolling a standard six-sided die.
**Example 115:** Creating a random sample for training and testing data.
**Example 116:** Generating random data points for plotting.
**Example 117:** Simulating random walks.

In [66]:
# Example 112: Demonstrating independent states with multiple Generator objects
import numpy as np

# Create two generators with the same seed
rng_a = np.random.default_rng(seed=100)
rng_b = np.random.default_rng(seed=100)

# Create a third generator with a different seed
rng_c = np.random.default_rng(seed=200)

print("\nExample 112: Independent states with Generator objects")
print("rng_a first call:", rng_a.random(3))
print("rng_b first call:", rng_b.random(3)) # Should be the same as rng_a first call
print("rng_c first call:", rng_c.random(3)) # Should be different

print("rng_a second call:", rng_a.random(3)) # Should be a continuation of rng_a's sequence
print("rng_b second call:", rng_b.random(3)) # Should be a continuation of rng_b's sequence (same as rng_a second call)


Example 112: Independent states with Generator objects
rng_a first call: [0.83498163 0.59655403 0.28886324]
rng_b first call: [0.83498163 0.59655403 0.28886324]
rng_c first call: [0.64683414 0.66391997 0.02990165]
rng_a second call: [0.04295157 0.9736544  0.5964717 ]
rng_b second call: [0.04295157 0.9736544  0.5964717 ]


**Step 5: Discuss State Management**

While we've touched upon setting seeds with both the older module-level functions (`np.random.seed()`) and the newer `Generator` (`np.random.default_rng(seed=...)`), let's briefly reiterate the difference in state management.

**Older Module-Level Functions:** These functions use a single, global random state. Setting the seed with `np.random.seed()` affects all subsequent calls to any of the module-level random functions *unless* the state is explicitly saved and restored.

**Newer `Generator` Class:** Each `Generator` object has its own independent random state. This makes it easier to manage multiple streams of random numbers or ensure reproducibility in different parts of your code without interfering with other parts. You set the seed when creating the `Generator` object.

**Example 112:** Demonstrating independent states with multiple `Generator` objects.

In [58]:
# Example 110: Generate samples from a Zipf distribution using Generator.zipf()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 110: Samples from Zipf distribution (a=2.0) using Generator.zipf():\n", rng.zipf(2.0, size=5))

# Example 111: Generate a 1D array from a Zipf distribution using Generator.zipf()
print("\nExample 111: 1D array from Zipf distribution (a=1.5) using Generator.zipf():\n", rng.zipf(1.5, size=5))


Example 110: Samples from Zipf distribution (a=2.0) using Generator.zipf():
 [4 1 1 1 1]

Example 111: 1D array from Zipf distribution (a=1.5) using Generator.zipf():
 [ 5 17 20  3  1]


**`Generator.zipf(a, size=None)`:** Draw samples from a Zipf distribution.

**Chain of Thought:**
1. The user needs random numbers from a Zipf distribution using the `Generator` object.
2. The `zipf()` method of the `Generator` object is used for this.
3. `a` is the distribution parameter.
4. `size` specifies the output shape.

**Example 110:** Generate samples from a Zipf distribution with parameter 2.0.
**Example 111:** Generate a 1D array from a Zipf distribution with parameter 1.5.

In [57]:
# Example 108: Generate samples from a Negative Binomial distribution using Generator.negative_binomial()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 108: Samples from Negative Binomial distribution (n=3, p=0.5) using Generator.negative_binomial():\n", rng.negative_binomial(3, 0.5, size=5))

# Example 109: Generate a 2x2 array from a Negative Binomial distribution using Generator.negative_binomial()
print("\nExample 109: 2x2 array from Negative Binomial distribution (n=5, p=0.8) using Generator.negative_binomial():\n", rng.negative_binomial(5, 0.8, size=(2, 2)))


Example 108: Samples from Negative Binomial distribution (n=3, p=0.5) using Generator.negative_binomial():
 [5 5 7 4 0]

Example 109: 2x2 array from Negative Binomial distribution (n=5, p=0.8) using Generator.negative_binomial():
 [[0 2]
 [0 0]]


**`Generator.negative_binomial(n, p, size=None)`:** Draw samples from a Negative Binomial distribution.

**Chain of Thought:**
1. The user needs random numbers from a Negative Binomial distribution using the `Generator` object.
2. The `negative_binomial()` method of the `Generator` object is used for this.
3. `n` is the number of successes and `p` is the probability of success in an individual trial.
4. `size` specifies the output shape.

**Example 108:** Generate samples from a Negative Binomial distribution (3 successes, prob 0.5).
**Example 109:** Generate a 2x2 array from a Negative Binomial distribution (5 successes, prob 0.8).

In [56]:
# Example 106: Generate samples from a Logarithmic Series distribution using Generator.logseries()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 106: Samples from Logarithmic Series distribution (p=0.6) using Generator.logseries():\n", rng.logseries(0.6, size=5))

# Example 107: Generate a 1D array from a Logarithmic Series distribution using Generator.logseries()
print("\nExample 107: 1D array from Logarithmic Series distribution (p=0.9) using Generator.logseries():\n", rng.logseries(0.9, size=5))


Example 106: Samples from Logarithmic Series distribution (p=0.6) using Generator.logseries():
 [1 2 1 5 1]

Example 107: 1D array from Logarithmic Series distribution (p=0.9) using Generator.logseries():
 [1 2 1 3 1]


**`Generator.logseries(p, size=None)`:** Draw samples from a Logarithmic Series distribution.

**Chain of Thought:**
1. The user needs random numbers from a Logarithmic Series distribution using the `Generator` object.
2. The `logseries()` method of the `Generator` object is used for this.
3. `p` is the shape parameter.
4. `size` specifies the output shape.

**Example 106:** Generate samples from a Logarithmic Series distribution with parameter 0.6.
**Example 107:** Generate a 1D array from a Logarithmic Series distribution with parameter 0.9.

In [55]:
# Example 104: Generate samples from a Hypergeometric distribution using Generator.hypergeometric()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 104: Samples from Hypergeometric distribution (ngood=10, nbad=15, nsample=5) using Generator.hypergeometric():\n", rng.hypergeometric(10, 15, 5, size=5))

# Example 105: Generate a 2x2 array from a Hypergeometric distribution using Generator.hypergeometric()
print("\nExample 105: 2x2 array from Hypergeometric distribution (ngood=5, nbad=10, nsample=3) using Generator.hypergeometric():\n", rng.hypergeometric(5, 10, 3, size=(2, 2)))


Example 104: Samples from Hypergeometric distribution (ngood=10, nbad=15, nsample=5) using Generator.hypergeometric():
 [4 1 2 1 2]

Example 105: 2x2 array from Hypergeometric distribution (ngood=5, nbad=10, nsample=3) using Generator.hypergeometric():
 [[1 1]
 [3 1]]


**`Generator.hypergeometric(ngood, nbad, nsample, size=None)`:** Draw samples from a Hypergeometric distribution.

**Chain of Thought:**
1. The user needs random numbers from a Hypergeometric distribution using the `Generator` object.
2. The `hypergeometric()` method of the `Generator` object is used for this.
3. `ngood` is the number of good items, `nbad` is the number of bad items, and `nsample` is the number of items drawn.
4. `size` specifies the output shape.

**Example 104:** Generate samples from a Hypergeometric distribution (10 good, 15 bad, 5 drawn).
**Example 105:** Generate a 2x2 array from a Hypergeometric distribution (5 good, 10 bad, 3 drawn).

In [54]:
# Example 102: Generate samples from a Geometric distribution using Generator.geometric()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 102: Samples from Geometric distribution (p=0.3) using Generator.geometric():\n", rng.geometric(0.3, size=5))

# Example 103: Generate a 1D array from a Geometric distribution using Generator.geometric()
print("\nExample 103: 1D array from Geometric distribution (p=0.7) using Generator.geometric():\n", rng.geometric(0.7, size=5))


Example 102: Samples from Geometric distribution (p=0.3) using Generator.geometric():
 [7 7 7 1 1]

Example 103: 1D array from Geometric distribution (p=0.7) using Generator.geometric():
 [4 2 2 1 1]


**4.6 More Methods for Discrete Distributions (Continued)**

Let's cover a couple more discrete distributions available through the `Generator` object.

**`Generator.geometric(p, size=None)`:** Draw samples from a Geometric distribution.

**Chain of Thought:**
1. The user needs random numbers from a Geometric distribution using the `Generator` object.
2. The `geometric()` method of the `Generator` object is used for this.
3. `p` is the probability of success.
4. `size` specifies the output shape.

**Example 102:** Generate samples from a Geometric distribution with probability 0.3.
**Example 103:** Generate a 1D array from a Geometric distribution with probability 0.7.

In [53]:
# Example 100: Generate samples from a Weibull distribution using Generator.weibull()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 100: Samples from Weibull distribution (a=1.5) using Generator.weibull():\n", rng.weibull(1.5, size=5))

# Example 101: Generate a 2x3 array from a Weibull distribution using Generator.weibull()
print("\nExample 101: 2x3 array from Weibull distribution (a=5.0) using Generator.weibull():\n", rng.weibull(5.0, size=(2, 3)))


Example 100: Samples from Weibull distribution (a=1.5) using Generator.weibull():
 [1.79465689 1.76064608 1.78496583 0.42778534 0.19549446]

Example 101: 2x3 array from Weibull distribution (a=5.0) using Generator.weibull():
 [[1.07753857 1.07112807 1.25588662]
 [0.60234912 1.00914343 0.58824645]]


**`Generator.weibull(a, size=None)`:** Draw samples from a Weibull distribution.

**Chain of Thought:**
1. The user needs random numbers from a Weibull distribution using the `Generator` object.
2. The `weibull()` method of the `Generator` object is used for this.
3. `a` is the shape parameter.
4. `size` specifies the output shape.

**Example 100:** Generate samples from a Weibull distribution with shape 1.5.
**Example 101:** Generate a 2x3 array from a Weibull distribution with shape 5.0.

In [52]:
# Example 98: Generate samples from a Wald (Inverse Gaussian) distribution using Generator.wald()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 98: Samples from Wald distribution (mean=1.0, scale=1.0) using Generator.wald():\n", rng.wald(1.0, 1.0, size=5))

# Example 99: Generate a 1D array from a Wald distribution using Generator.wald()
print("\nExample 99: 1D array from Wald distribution (mean=3.0, scale=2.0) using Generator.wald():\n", rng.wald(3.0, 2.0, size=5))


Example 98: Samples from Wald distribution (mean=1.0, scale=1.0) using Generator.wald():
 [0.73819274 2.08313019 5.62888317 1.13627289 0.98333939]

Example 99: 1D array from Wald distribution (mean=3.0, scale=2.0) using Generator.wald():
 [8.40986137 3.25262065 1.70502383 1.91695759 1.07126652]


**`Generator.wald(mean, scale, size=None)`:** Draw samples from a Wald (Inverse Gaussian) distribution.

**Chain of Thought:**
1. The user needs random numbers from a Wald distribution using the `Generator` object.
2. The `wald()` method of the `Generator` object is used for this.
3. `mean` and `scale` are the parameters of the Wald distribution.
4. `size` specifies the output shape.

**Example 98:** Generate samples from a Wald distribution with mean=1.0 and scale=1.0.
**Example 99:** Generate a 1D array from a Wald distribution with mean=3.0 and scale=2.0.

In [51]:
# Example 96: Generate samples from a Von Mises distribution using Generator.vonmises()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 96: Samples from Von Mises distribution (mu=0.0, kappa=1.0) using Generator.vonmises():\n", rng.vonmises(0.0, 1.0, size=5))

# Example 97: Generate a 2x2 array from a Von Mises distribution using Generator.vonmises()
print("\nExample 97: 2x2 array from Von Mises distribution (mu=np.pi, kappa=10.0) using Generator.vonmises():\n", rng.vonmises(np.pi, 10.0, size=(2, 2)))


Example 96: Samples from Von Mises distribution (mu=0.0, kappa=1.0) using Generator.vonmises():
 [ 1.83788195  1.51309604 -1.77921639  0.78755978 -1.31984354]

Example 97: 2x2 array from Von Mises distribution (mu=np.pi, kappa=10.0) using Generator.vonmises():
 [[ 3.0238381   2.32001774]
 [-3.1198073   2.96447755]]


**`Generator.vonmises(mu, kappa, size=None)`:** Draw samples from a Von Mises distribution.

**Chain of Thought:**
1. The user needs random numbers from a Von Mises distribution using the `Generator` object.
2. The `vonmises()` method of the `Generator` object is used for this.
3. `mu` is the mean angle and `kappa` is the concentration parameter.
4. `size` specifies the output shape.

**Example 96:** Generate samples from a Von Mises distribution with mu=0.0 and kappa=1.0.
**Example 97:** Generate a 2x2 array from a Von Mises distribution with mu=np.pi and kappa=10.0.

In [50]:
# Example 94: Generate samples from a triangular distribution using Generator.triangular()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 94: Samples from triangular distribution (left=0, mode=0.5, right=1) using Generator.triangular():\n", rng.triangular(0, 0.5, 1, size=5))

# Example 95: Generate a 1D array from a triangular distribution using Generator.triangular()
print("\nExample 95: 1D array from triangular distribution (left=-3, mode=0, right=3) using Generator.triangular():\n", rng.triangular(-3, 0, 3, size=5))


Example 94: Samples from triangular distribution (left=0, mode=0.5, right=1) using Generator.triangular():
 [0.66381259 0.4684434  0.73410333 0.61100645 0.21699925]

Example 95: 1D array from triangular distribution (left=-3, mode=0, right=3) using Generator.triangular():
 [ 2.33758195  0.92647996  1.03764363 -1.48143311 -0.15272992]


**`Generator.triangular(left, mode, right, size=None)`:** Draw samples from a triangular distribution.

**Chain of Thought:**
1. The user needs random numbers from a triangular distribution using the `Generator` object.
2. The `triangular()` method of the `Generator` object is used for this.
3. `left`, `mode`, and `right` are the parameters defining the distribution's shape.
4. `size` specifies the output shape.

**Example 94:** Generate samples from a triangular distribution with left=0, mode=0.5, right=1.
**Example 95:** Generate a 1D array from a triangular distribution with left=-3, mode=0, right=3.

In [49]:
# Example 92: Generate samples from a standard Student's t distribution using Generator.standard_t()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 92: Samples from standard Student's t distribution (df=10) using Generator.standard_t():\n", rng.standard_t(10, size=5))

# Example 93: Generate a 2x4 array from a standard Student's t distribution using Generator.standard_t()
print("\nExample 93: 2x4 array from standard Student's t distribution (df=2) using Generator.standard_t():\n", rng.standard_t(2, size=(2, 4)))


Example 92: Samples from standard Student's t distribution (df=10) using Generator.standard_t():
 [ 0.4100402   0.94546385 -0.02149125  0.79294169  0.59901342]

Example 93: 2x4 array from standard Student's t distribution (df=2) using Generator.standard_t():
 [[-1.01007825 -0.04470186 -0.50226503 -0.19082133]
 [-0.52300413  0.86224116  0.69103595 -0.48283939]]


**`Generator.standard_t(df, size=None)`:** Draw samples from a standard Student's t distribution.

**Chain of Thought:**
1. The user needs random numbers from a standard Student's t distribution using the `Generator` object.
2. The `standard_t()` method of the `Generator` object is used for this.
3. `df` is the degrees of freedom parameter.
4. `size` specifies the output shape.

**Example 92:** Generate samples from a standard Student's t distribution with df=10.
**Example 93:** Generate a 2x4 array from a standard Student's t distribution with df=2.

In [48]:
# Example 90: Generate samples from a standard Gamma distribution using Generator.standard_gamma()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 90: Samples from standard Gamma distribution (shape=2.0) using Generator.standard_gamma():\n", rng.standard_gamma(2.0, size=5))

# Example 91: Generate a 1D array from a standard Gamma distribution using Generator.standard_gamma()
print("\nExample 91: 1D array from standard Gamma distribution (shape=5.0) using Generator.standard_gamma():\n", rng.standard_gamma(5.0, size=5))


Example 90: Samples from standard Gamma distribution (shape=2.0) using Generator.standard_gamma():
 [2.09181727 2.83534559 1.83721558 1.64507042 3.07925533]

Example 91: 1D array from standard Gamma distribution (shape=5.0) using Generator.standard_gamma():
 [4.81076756 5.75120915 5.50944479 6.83318328 4.27860137]


**`Generator.standard_gamma(shape, size=None)`:** Draw samples from a standard Gamma distribution.

**Chain of Thought:**
1. The user needs random numbers from a standard Gamma distribution using the `Generator` object.
2. The `standard_gamma()` method of the `Generator` object is used for this.
3. The standard Gamma distribution has a scale of 1.0.
4. `shape` (k) is the shape parameter.
5. `size` specifies the output shape.

**Example 90:** Generate samples from a standard Gamma distribution with shape 2.0.
**Example 91:** Generate a 1D array from a standard Gamma distribution with shape 5.0.

In [47]:
# Example 88: Generate samples from a standard Cauchy distribution using Generator.standard_cauchy()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 88: Samples from standard Cauchy distribution using Generator.standard_cauchy():\n", rng.standard_cauchy(size=5))

# Example 89: Generate a 2x3 array from a standard Cauchy distribution using Generator.standard_cauchy()
print("\nExample 89: 2x3 array from standard Cauchy distribution using Generator.standard_cauchy():\n", rng.standard_cauchy(size=(2, 3)))


Example 88: Samples from standard Cauchy distribution using Generator.standard_cauchy():
 [-0.29300167  0.797873    1.49828436 -0.4042479   0.01969554]

Example 89: 2x3 array from standard Cauchy distribution using Generator.standard_cauchy():
 [[  1.13063396   0.05857726  -0.54406312]
 [ -0.38456302 -17.59507807   0.2714853 ]]


**`Generator.standard_cauchy(size=None)`:** Draw samples from a standard Cauchy distribution.

**Chain of Thought:**
1. The user needs random numbers from a standard Cauchy distribution using the `Generator` object.
2. The `standard_cauchy()` method of the `Generator` object is used for this.
3. The standard Cauchy distribution has a location of 0 and a scale of 1.
4. `size` specifies the output shape.

**Example 88:** Generate samples from a standard Cauchy distribution.
**Example 89:** Generate a 2x3 array from a standard Cauchy distribution.

In [46]:
# Example 86: Generate samples from a Rayleigh distribution using Generator.rayleigh()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 86: Samples from Rayleigh distribution (scale=1.0) using Generator.rayleigh():\n", rng.rayleigh(size=5))

# Example 87: Generate a 1D array from a Rayleigh distribution using Generator.rayleigh()
print("\nExample 87: 1D array from Rayleigh distribution (scale=3.0) using Generator.rayleigh():\n", rng.rayleigh(scale=3.0, size=5))


Example 86: Samples from Rayleigh distribution (scale=1.0) using Generator.rayleigh():
 [2.19281034 2.16156872 2.18392353 0.74805654 0.41578215]

Example 87: 1D array from Rayleigh distribution (scale=3.0) using Generator.rayleigh():
 [5.11350069 5.03778647 7.4991551  1.19469475 4.34028746]


**`Generator.rayleigh(scale=1.0, size=None)`:** Draw samples from a Rayleigh distribution.

**Chain of Thought:**
1. The user needs random numbers from a Rayleigh distribution using the `Generator` object.
2. The `rayleigh()` method of the `Generator` object is used for this.
3. `scale` is the scale parameter.
4. `size` specifies the output shape.

**Example 86:** Generate samples from a Rayleigh distribution with default scale.
**Example 87:** Generate a 1D array from a Rayleigh distribution with scale 3.0.

In [45]:
# Example 84: Generate samples from a Power distribution using Generator.power()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 84: Samples from Power distribution (a=2.0) using Generator.power():\n", rng.power(2.0, size=5))

# Example 85: Generate a 2x2 array from a Power distribution using Generator.power()
print("\nExample 85: 2x2 array from Power distribution (a=5.0) using Generator.power():\n", rng.power(5.0, size=(2, 2)))


Example 84: Samples from Power distribution (a=2.0) using Generator.power():
 [0.95376257 0.95042339 0.9528321  0.49402507 0.28776212]

Example 85: 2x2 array from Power distribution (a=5.0) using Generator.power():
 [[0.94809479 0.94555499]
 [0.99104756 0.59762304]]


**`Generator.power(a, size=None)`:** Draw samples from a Power distribution.

**Chain of Thought:**
1. The user needs random numbers from a Power distribution using the `Generator` object.
2. The `power()` method of the `Generator` object is used for this.
3. `a` is the exponent parameter.
4. `size` specifies the output shape.

**Example 84:** Generate samples from a Power distribution with exponent 2.0.
**Example 85:** Generate a 2x2 array from a Power distribution with exponent 5.0.

In [44]:
# Example 82: Generate samples from a Logistic distribution using Generator.logistic()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 82: Samples from Logistic distribution (loc=0, scale=1) using Generator.logistic():\n", rng.logistic(size=5))

# Example 83: Generate a 1D array from a Logistic distribution using Generator.logistic()
print("\nExample 83: 1D array from Logistic distribution (loc=5.0, scale=2.0) using Generator.logistic():\n", rng.logistic(loc=5.0, scale=2.0, size=5))


Example 82: Samples from Logistic distribution (loc=0, scale=1) using Generator.logistic():
 [ 1.23078563 -0.24571509  1.80369327  0.83479584 -2.26366385]

Example 83: 1D array from Logistic distribution (loc=5.0, scale=2.0) using Generator.logistic():
 [12.37881783  7.31787613  7.60272625  1.16451705  4.60177706]


**`Generator.logistic(loc=0.0, scale=1.0, size=None)`:** Draw samples from a Logistic distribution.

**Chain of Thought:**
1. The user needs random numbers from a Logistic distribution using the `Generator` object.
2. The `logistic()` method of the `Generator` object is used for this.
3. `loc` is the mean and `scale` is the scale parameter.
4. `size` specifies the output shape.

**Example 82:** Generate samples from a Logistic distribution with default parameters.
**Example 83:** Generate a 1D array from a Logistic distribution with mean 5.0 and scale 2.0.

In [43]:
# Example 80: Generate samples from a Gamma distribution using Generator.gamma()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 80: Samples from Gamma distribution (shape=2.0, scale=1.0) using Generator.gamma():\n", rng.gamma(2.0, size=5))

# Example 81: Generate a 3x3 array from a Gamma distribution using Generator.gamma()
print("\nExample 81: 3x3 array from Gamma distribution (shape=5.0, scale=0.5) using Generator.gamma():\n", rng.gamma(5.0, scale=0.5, size=(3, 3)))


Example 80: Samples from Gamma distribution (shape=2.0, scale=1.0) using Generator.gamma():
 [2.09181727 2.83534559 1.83721558 1.64507042 3.07925533]

Example 81: 3x3 array from Gamma distribution (shape=5.0, scale=0.5) using Generator.gamma():
 [[2.40538378 2.87560457 2.75472239]
 [3.41659164 2.13930069 3.91859379]
 [1.90059022 2.95681147 2.80812958]]


**`Generator.gamma(shape, scale=1.0, size=None)`:** Draw samples from a Gamma distribution.

**Chain of Thought:**
1. The user needs random numbers from a Gamma distribution using the `Generator` object.
2. The `gamma()` method of the `Generator` object is used for this.
3. `shape` (k) and `scale` (theta) are the parameters of the Gamma distribution.
4. `size` specifies the output shape.

**Example 80:** Generate samples from a Gamma distribution with shape 2.0 and default scale.
**Example 81:** Generate a 3x3 array from a Gamma distribution with shape 5.0 and scale 0.5.

In [42]:
# Example 78: Generate samples from an Exponential distribution using Generator.exponential()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 78: Samples from Exponential distribution (scale=1.0) using Generator.exponential():\n", rng.exponential(size=5))

# Example 79: Generate a 1D array from an Exponential distribution using Generator.exponential()
print("\nExample 79: 1D array from Exponential distribution (scale=2.0) using Generator.exponential():\n", rng.exponential(scale=2.0, size=5))


Example 78: Samples from Exponential distribution (scale=1.0) using Generator.exponential():
 [2.4042086  2.33618966 2.384761   0.27979429 0.0864374 ]

Example 79: 1D array from Exponential distribution (scale=2.0) using Generator.exponential():
 [2.90532103 2.81992139 6.24859191 0.15858839 2.09312169]


**`Generator.exponential(scale=1.0, size=None)`:** Draw samples from an exponential distribution.

**Chain of Thought:**
1. The user needs random numbers from an exponential distribution using the `Generator` object.
2. The `exponential()` method of the `Generator` object is used for this.
3. `scale` is the scale parameter (inverse of the rate).
4. `size` specifies the output shape.

**Example 78:** Generate samples from an exponential distribution with default scale (1.0).
**Example 79:** Generate a 1D array from an exponential distribution with scale 2.0.

In [41]:
# Example 76: Generate samples from a Beta distribution using Generator.beta()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 76: Samples from Beta distribution (a=2, b=5) using Generator.beta():\n", rng.beta(2, 5, size=5))

# Example 77: Generate a 2x2 array from a Beta distribution using Generator.beta()
print("\nExample 77: 2x2 array from Beta distribution (a=0.5, b=0.5) using Generator.beta():\n", rng.beta(0.5, 0.5, size=(2, 2)))


Example 76: Samples from Beta distribution (a=2, b=5) using Generator.beta():
 [0.24395464 0.28406092 0.39027204 0.29864681 0.41835336]

Example 77: 2x2 array from Beta distribution (a=0.5, b=0.5) using Generator.beta():
 [[0.9411521  0.99126829]
 [0.04854636 0.43615879]]


**4.5 More Methods for Continuous Distributions (Continued)**

Let's continue demonstrating more distribution methods from the `Generator` class.

**`Generator.beta(a, b, size=None)`:** Draw samples from a Beta distribution.

**Chain of Thought:**
1. The user needs random numbers from a Beta distribution using the `Generator` object.
2. The `beta()` method of the `Generator` object is used for this.
3. `a` and `b` are the shape parameters of the Beta distribution.
4. `size` specifies the output shape.

**Example 76:** Generate samples from a Beta distribution with parameters a=2 and b=5.
**Example 77:** Generate a 2x2 array from a Beta distribution with parameters a=0.5 and b=0.5.

Let's demonstrate a few more distribution methods from the `Generator` class.

**Example 70:** Generate samples from a Beta distribution using `Generator.beta()`.
**Example 71:** Generate samples from a Logistic distribution using `Generator.logistic()`.
**Example 72:** Generate samples from a Gamma distribution using `Generator.gamma()`.
**Example 73:** Generate samples from an Exponential distribution using `Generator.exponential()`.
**Example 74:** Generate samples from a Chi-square distribution using `Generator.chisquare()`.
**Example 75:** Generate samples from a standard T distribution using `Generator.standard_t()`.

In [34]:
# Example 69: Generate a string of 10 random bytes using Generator.bytes()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 69: 10 random bytes using Generator.bytes():", rng.bytes(10))


Example 69: 10 random bytes using Generator.bytes(): b'\x88&\xd9\x16\xcd\xfb!\xc6\xc1\xff'


**4.4 Other Useful Methods of the `Generator` Class**

The `Generator` class also provides methods for generating random numbers from many other distributions, similar to the older module-level functions but accessed as methods of the `Generator` object.

**`Generator.bytes(length)`:** Return random bytes. This is the `Generator` equivalent of `np.random.bytes()`.

**Chain of Thought:**
1. The user might need random bytes using the `Generator` object.
2. The `bytes()` method of the `Generator` object is used for this.

**Example 69:** Generate a string of 10 random bytes using `Generator.bytes()`.

In [33]:
# Example 66: Get a random permutation of an integer range using Generator.permutation()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 66: Random permutation of range 10 using Generator.permutation():", rng.permutation(10))

# Example 67: Get a random permutation of a 1D array using Generator.permutation()
original_array = np.arange(10)
print("\nExample 67: Original 1D array:", original_array)
permuted_array = rng.permutation(original_array)
print("Permuted 1D array (new) using Generator.permutation():", permuted_array)
print("Original 1D array after permutation:", original_array) # Original is unchanged

# Example 68: Get a random permutation of rows in a 2D array using Generator.permutation()
arr_2d = np.arange(12).reshape(4, 3)
print("\nExample 68: Original 2D array:\n", arr_2d)
permuted_arr_2d = rng.permutation(arr_2d) # Permutes rows
print("Permuted 2D array (rows permuted, new) using Generator.permutation():\n", permuted_arr_2d)
print("Original 2D array after permutation:\n", arr_2d) # Original is unchanged


Example 66: Random permutation of range 10 using Generator.permutation(): [5 6 0 7 3 2 4 9 1 8]

Example 67: Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Permuted 1D array (new) using Generator.permutation(): [4 8 2 6 5 9 7 3 0 1]
Original 1D array after permutation: [0 1 2 3 4 5 6 7 8 9]

Example 68: Original 2D array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Permuted 2D array (rows permuted, new) using Generator.permutation():
 [[ 0  1  2]
 [ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]]
Original 2D array after permutation:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


**`Generator.permutation(x, axis=0)`:** Randomly permute a sequence, or return a permuted range, without modifying the original. This is the `Generator` equivalent of `np.random.permutation()`.

**Chain of Thought:**
1. The user wants a random reordering that returns a new array, not modifying the original, using the `Generator` object.
2. The `permutation()` method of the `Generator` object is used for this.
3. Similar to `np.random.permutation()`, it works on integers or arrays.

**Example 66:** Get a random permutation of an integer range using `Generator.permutation()`.
**Example 67:** Get a random permutation of a 1D array using `Generator.permutation()`.
**Example 68:** Get a random permutation of rows in a 2D array using `Generator.permutation()`.

In [32]:
# Example 64: Shuffle a 1D array in-place using Generator.shuffle()
import numpy as np

rng = np.random.default_rng(seed=42)
arr_1d_to_shuffle = np.arange(10)
print("\nExample 64: Original 1D array:", arr_1d_to_shuffle)
rng.shuffle(arr_1d_to_shuffle)
print("Shuffled 1D array (in-place) using Generator.shuffle():", arr_1d_to_shuffle)

# Example 65: Shuffle rows of a 2D array in-place using Generator.shuffle()
arr_2d_to_shuffle = np.arange(12).reshape(4, 3)
print("\nExample 65: Original 2D array:\n", arr_2d_to_shuffle)
rng.shuffle(arr_2d_to_shuffle) # Shuffles rows
print("Shuffled 2D array (rows shuffled in-place) using Generator.shuffle():\n", arr_2d_to_shuffle)


Example 64: Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Shuffled 1D array (in-place) using Generator.shuffle(): [5 6 0 7 3 2 4 9 1 8]

Example 65: Original 2D array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shuffled 2D array (rows shuffled in-place) using Generator.shuffle():
 [[ 6  7  8]
 [ 9 10 11]
 [ 0  1  2]
 [ 3  4  5]]


**4.3 Methods for Permutations and Shuffling**

The `Generator` object also has methods for randomly reordering elements.

**`Generator.shuffle(x, axis=0)`:** Modify a sequence in-place by shuffling its contents along an axis. This is the `Generator` equivalent of `np.random.shuffle()`.

**Chain of Thought:**
1. The user wants to randomly reorder array elements in-place using the `Generator` object.
2. The `shuffle()` method of the `Generator` object is used for this.
3. By default, it shuffles along the first axis.

**Example 64:** Shuffle a 1D array in-place using `Generator.shuffle()`.
**Example 65:** Shuffle rows of a 2D array in-place using `Generator.shuffle()`.

In [31]:
# Example 62: Simulate a single event count with an average rate of 3 using Generator.poisson()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 62: Poisson(lam=3) single event using Generator.poisson():", rng.poisson(3))

# Example 63: Simulate event counts with an average rate of 5, repeated 6 times using Generator.poisson()
print("\nExample 63: Poisson(lam=5) 6 events using Generator.poisson():\n", rng.poisson(5, size=6))


Example 62: Poisson(lam=3) single event using Generator.poisson(): 4

Example 63: Poisson(lam=5) 6 events using Generator.poisson():
 [8 3 9 6 3 8]


**`Generator.poisson(lam=1.0, size=None)`:** Draw samples from a Poisson distribution using the `Generator` object. This is the `Generator` equivalent of `np.random.poisson()`.

**Chain of Thought:**
1. The user wants to simulate event counts given an average rate using the `Generator` object.
2. The `poisson()` method of the `Generator` object is used for this.
3. `lam` is the average rate.
4. `size` specifies the output shape.

**Example 62:** Simulate a single event count with an average rate of 3 using `Generator.poisson()`.
**Example 63:** Simulate event counts with an average rate of 5, repeated 6 times using `Generator.poisson()`.

In [30]:
# Example 60: Simulate 10 trials with a 50% success rate once using Generator.binomial()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 60: Binomial(n=10, p=0.5) single trial using Generator.binomial():", rng.binomial(10, 0.5))

# Example 61: Simulate 10 trials with a 30% success rate, repeated 5 times using Generator.binomial()
print("\nExample 61: Binomial(n=10, p=0.3) 5 trials using Generator.binomial():\n", rng.binomial(10, 0.3, size=5))


Example 60: Binomial(n=10, p=0.5) single trial using Generator.binomial(): 6

Example 61: Binomial(n=10, p=0.3) 5 trials using Generator.binomial():
 [3 5 4 1 6]


**`Generator.binomial(n, p, size=None)`:** Draw samples from a binomial distribution using the `Generator` object. This is the `Generator` equivalent of `np.random.binomial()`.

**Chain of Thought:**
1. The user wants to simulate the number of successes in a series of independent Bernoulli trials using the `Generator` object.
2. The `binomial()` method of the `Generator` object is used for this.
3. `n` is the number of trials, and `p` is the probability of success.
4. `size` specifies the output shape.

**Example 60:** Simulate 10 trials with a 50% success rate once using `Generator.binomial()`.
**Example 61:** Simulate 10 trials with a 30% success rate, repeated 5 times using `Generator.binomial()`.

In [29]:
# Example 55: Randomly pick a single element from an array using Generator.choice()
import numpy as np

rng = np.random.default_rng(seed=42)
elements = [1, 2, 3, 4, 5]
print("\nExample 55: Randomly pick a single element using Generator.choice():", rng.choice(elements))

# Example 56: Randomly pick 5 elements with replacement using Generator.choice()
print("\nExample 56: Randomly pick 5 elements with replacement using Generator.choice():\n", rng.choice(elements, size=5, replace=True))

# Example 57: Randomly pick 3 elements without replacement using Generator.choice()
print("\nExample 57: Randomly pick 3 elements without replacement using Generator.choice():\n", rng.choice(elements, size=3, replace=False))

# Example 58: Randomly pick elements with specified probabilities using Generator.choice()
probabilities = [0.1, 0.2, 0.3, 0.2, 0.2]
print("\nExample 58: Randomly pick elements with probabilities using Generator.choice():\n", rng.choice(elements, size=10, p=probabilities))

# Example 59: Randomly pick from an integer range using Generator.choice()
print("\nExample 59: Randomly pick from integer range [0, 10) (size 5) using Generator.choice():\n", rng.choice(10, size=5))


Example 55: Randomly pick a single element using Generator.choice(): 1

Example 56: Randomly pick 5 elements with replacement using Generator.choice():
 [4 4 3 3 5]

Example 57: Randomly pick 3 elements without replacement using Generator.choice():
 [2 3 1]

Example 58: Randomly pick elements with probabilities using Generator.choice():
 [4 4 2 3 3 5 4 5 3 2]

Example 59: Randomly pick from integer range [0, 10) (size 5) using Generator.choice():
 [9 0 5 8 0]


**`Generator.choice(a, size=None, replace=True, p=None, axis=0)`:** Generates a random sample from a given 1-D array (`a`) or from an integer range. This is the `Generator` equivalent of `np.random.choice()`.

**Chain of Thought:**
1. The user wants to randomly select elements from an existing array or a range using the `Generator` object.
2. The `choice()` method of the `Generator` object is used for this.
3. `a` is the array or integer range to sample from.
4. `size` is the number of samples to draw.
5. `replace=True` (default) means sampling with replacement, `replace=False` means sampling without replacement.
6. `p` allows specifying the probabilities.

**Example 55:** Randomly pick a single element from an array using `Generator.choice()`.
**Example 56:** Randomly pick 5 elements with replacement using `Generator.choice()`.
**Example 57:** Randomly pick 3 elements without replacement using `Generator.choice()`.
**Example 58:** Randomly pick elements with specified probabilities using `Generator.choice()`.
**Example 59:** Randomly pick from an integer range using `Generator.choice()`.

In [28]:
# Example 51: Generate a single random integer between 0 and 10 (exclusive) using Generator.integers()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 51: Single random integer [0, 10) using Generator.integers():", rng.integers(10))

# Example 52: Generate a 1D array of random integers between 1 and 7 (exclusive) using Generator.integers()
print("\nExample 52: 1D array of random integers [1, 7) using Generator.integers():\n", rng.integers(1, 7, size=8))

# Example 53: Generate a 2x4 array of random integers between 50 and 100 (exclusive) using Generator.integers()
print("\nExample 53: 2x4 array of random integers [50, 100) using Generator.integers():\n", rng.integers(50, 100, size=(2, 4)))

# Example 54: Generate a single random integer between 0 and 10 (inclusive) using Generator.integers() with endpoint=True
print("\nExample 54: Single random integer [0, 10] using Generator.integers(endpoint=True):", rng.integers(0, 10, endpoint=True))


Example 51: Single random integer [0, 10) using Generator.integers(): 0

Example 52: 1D array of random integers [1, 7) using Generator.integers():
 [5 4 3 3 6 1 5 2]

Example 53: 2x4 array of random integers [50, 100) using Generator.integers():
 [[54 76 98 86]
 [88 85 89 75]]

Example 54: Single random integer [0, 10] using Generator.integers(endpoint=True): 1


**4.2 Methods for Discrete Distributions**

The `Generator` object also has methods for drawing samples from discrete probability distributions.

**`Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)`:** Return random integers from `low` (inclusive) to `high` (exclusive by default, or inclusive if `endpoint=True`). This is the `Generator` equivalent of `np.random.randint()`.

**Chain of Thought:**
1. The user wants random integers within a specified range using the `Generator` object.
2. The `integers()` method of the `Generator` object is used for this.
3. `low` is the lower bound (inclusive), and `high` is the upper bound (exclusive by default).
4. `size` specifies the output shape.

**Example 51:** Generate a single random integer between 0 and 10 (exclusive) using `Generator.integers()`.
**Example 52:** Generate a 1D array of random integers between 1 and 7 (exclusive) using `Generator.integers()`.
**Example 53:** Generate a 2x4 array of random integers between 50 and 100 (exclusive) using `Generator.integers()`.
**Example 54:** Generate a single random integer between 0 and 10 (inclusive) using `Generator.integers()` with `endpoint=True`.

In [27]:
# Example 48: Generate a single normal random number using Generator.normal()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 48: Single normal random number using Generator.normal():", rng.normal())

# Example 49: Generate a 1D array from a normal distribution using Generator.normal()
print("\nExample 49: 1D array from normal (mean=10, std=2) using Generator.normal():\n", rng.normal(loc=10, scale=2, size=7))

# Example 50: Generate a 3x3 array from a normal distribution using Generator.normal()
print("\nExample 50: 3x3 array from normal (mean=-5, std=0.5) using Generator.normal():\n", rng.normal(loc=-5, scale=0.5, size=(3, 3)))


Example 48: Single normal random number using Generator.normal(): 0.30471707975443135

Example 49: 1D array from normal (mean=10, std=2) using Generator.normal():
 [ 7.92003179 11.50090239 11.88112943  6.09792962  7.39564099 10.25568081
  9.36751482]

Example 50: 3x3 array from normal (mean=-5, std=0.5) using Generator.normal():
 [[-5.00840058 -5.42652196 -4.56030101]
 [-4.61110403 -4.96698465 -4.4363794 ]
 [-4.76624533 -5.42964623 -4.81562461]]


**`Generator.normal(loc=0.0, scale=1.0, size=None, dtype=np.float64)`:** Draw random samples from a normal (Gaussian) distribution. This is the `Generator` equivalent of `np.random.normal()`.

**Chain of Thought:**
1. The user wants random numbers from a normal distribution with specific mean and standard deviation using the `Generator` object.
2. The `normal()` method of the `Generator` object is used for this.
3. `loc` is the mean and `scale` is the standard deviation.
4. `size` specifies the output shape.

**Example 48:** Generate a single normal random number using `Generator.normal()`.
**Example 49:** Generate a 1D array from a normal distribution using `Generator.normal()`.
**Example 50:** Generate a 3x3 array from a normal distribution using `Generator.normal()`.

In [26]:
# Example 45: Generate a single uniform random float between 5 and 10 using Generator.uniform()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 45: Single uniform random float [5, 10) using Generator.uniform():", rng.uniform(5, 10))

# Example 46: Generate a 1D array of uniform random floats between -1 and 1 using Generator.uniform()
print("\nExample 46: 1D array of uniform random floats [-1, 1) using Generator.uniform():\n", rng.uniform(-1, 1, size=6))

# Example 47: Generate a 2x3 array of uniform random floats between 100 and 200 using Generator.uniform()
print("\nExample 47: 2x3 array of uniform random floats [100, 200) using Generator.uniform():\n", rng.uniform(100, 200, size=(2, 3)))


Example 45: Single uniform random float [5, 10) using Generator.uniform(): 8.869780242779816

Example 46: 1D array of uniform random floats [-1, 1) using Generator.uniform():
 [-0.12224312  0.71719584  0.39473606 -0.8116453   0.9512447   0.5222794 ]

Example 47: 2x3 array of uniform random floats [100, 200) using Generator.uniform():
 [[178.60643053 112.81136327 145.03859379]
 [137.07980242 192.67649888 164.38651201]]


**`Generator.uniform(low=0.0, high=1.0, size=None, dtype=np.float64)`:** Draw samples from a uniform distribution over the interval `[low, high)`. This is the `Generator` equivalent of `np.random.uniform()`.

**Chain of Thought:**
1. The user wants uniform random numbers within a specific range other than [0, 1) using the `Generator` object.
2. The `uniform()` method of the `Generator` object is used for this.
3. The `low` and `high` arguments specify the bounds.
4. The `size` argument specifies the output shape.

**Example 45:** Generate a single uniform random float between 5 and 10 using `Generator.uniform()`.
**Example 46:** Generate a 1D array of uniform random floats between -1 and 1 using `Generator.uniform()`.
**Example 47:** Generate a 2x3 array of uniform random floats between 100 and 200 using `Generator.uniform()`.

In [25]:
# Example 42: Generate a single standard normal random number using Generator.standard_normal()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 42: Single standard normal random number using Generator.standard_normal():", rng.standard_normal())

# Example 43: Generate a 1D array from standard normal using Generator.standard_normal()
print("\nExample 43: 1D array from standard normal using Generator.standard_normal():\n", rng.standard_normal(4))

# Example 44: Generate a 3x2 array from standard normal using Generator.standard_normal()
print("\nExample 44: 3x2 array from standard normal using Generator.standard_normal():\n", rng.standard_normal((3, 2)))


Example 42: Single standard normal random number using Generator.standard_normal(): 0.30471707975443135

Example 43: 1D array from standard normal using Generator.standard_normal():
 [-1.03998411  0.7504512   0.94056472 -1.95103519]

Example 44: 3x2 array from standard normal using Generator.standard_normal():
 [[-1.30217951  0.1278404 ]
 [-0.31624259 -0.01680116]
 [-0.85304393  0.87939797]]


**`Generator.standard_normal(size=None, dtype=np.float64, out=None)`:** Draw samples from the standard normal distribution (mean=0, variance=1). This is the `Generator` equivalent of `np.random.randn()`.

**Chain of Thought:**
1. The user wants random numbers from a standard normal distribution using the `Generator` object.
2. The `standard_normal()` method of the `Generator` object is used for this.
3. The `size` argument specifies the output shape.

**Example 42:** Generate a single standard normal random number using `Generator.standard_normal()`.
**Example 43:** Generate a 1D array from standard normal using `Generator.standard_normal()`.
**Example 44:** Generate a 3x2 array from standard normal using `Generator.standard_normal()`.

In [24]:
# Example 39: Generate a single random float using Generator.random()
import numpy as np

rng = np.random.default_rng(seed=42)
print("\nExample 39: Single uniform random float using Generator.random():", rng.random())

# Example 40: Generate a 1D array of uniform random floats using Generator.random()
print("\nExample 40: 1D array of uniform random floats using Generator.random():\n", rng.random(5))

# Example 41: Generate a 2x2 array of uniform random floats using Generator.random()
print("\nExample 41: 2x2 array of uniform random floats using Generator.random():\n", rng.random((2, 2)))


Example 39: Single uniform random float using Generator.random(): 0.7739560485559633

Example 40: 1D array of uniform random floats using Generator.random():
 [0.43887844 0.85859792 0.69736803 0.09417735 0.97562235]

Example 41: 2x2 array of uniform random floats using Generator.random():
 [[0.7611397  0.78606431]
 [0.12811363 0.45038594]]


**4.1 Methods for Continuous Distributions**

The `Generator` object has methods similar to the older module-level functions for drawing samples from continuous distributions.

**`Generator.random(size=None, dtype=np.float64)`:** Return random floats in the half-open interval `[0.0, 1.0)`. This is the `Generator` equivalent of `np.random.rand()`.

**Chain of Thought:**
1. The user needs uniform random numbers between 0 and 1 using the `Generator` object.
2. The `random()` method of the `Generator` object is used for this.
3. The `size` argument specifies the output shape.

**Example 39:** Generate a single random float using `Generator.random()`.
**Example 40:** Generate a 1D array of uniform random floats using `Generator.random()`.
**Example 41:** Generate a 2x2 array of uniform random floats using `Generator.random()`.

In [23]:
# Example 37: Create a Generator object without a seed
import numpy as np

# Create a default generator
rng1 = np.random.default_rng()
print("\nExample 37: Generator object created without a seed:", rng1)
print("Random numbers from rng1:", rng1.random(3))

# Example 38: Create a Generator object with a seed for reproducibility
rng2 = np.random.default_rng(seed=123)
print("\nExample 38: Generator object created with seed 123:", rng2)
print("Random numbers from rng2 (seed 123, first call):", rng2.random(3))

rng3 = np.random.default_rng(seed=123) # Create another generator with the same seed
print("Random numbers from rng3 (seed 123, should be the same as rng2 first call):", rng3.random(3))

rng2_more = rng2.random(3) # Generate more numbers from the first generator
print("Random numbers from rng2 (seed 123, second call):", rng2_more)


Example 37: Generator object created without a seed: Generator(PCG64)
Random numbers from rng1: [0.70613867 0.65978311 0.9436303 ]

Example 38: Generator object created with seed 123: Generator(PCG64)
Random numbers from rng2 (seed 123, first call): [0.68235186 0.05382102 0.22035987]
Random numbers from rng3 (seed 123, should be the same as rng2 first call): [0.68235186 0.05382102 0.22035987]
Random numbers from rng2 (seed 123, second call): [0.18437181 0.1759059  0.81209451]


**Step 3: Introduce the `Generator` Class (`np.random.default_rng()`)**

As mentioned earlier, the `Generator` class is the preferred way to generate random numbers in modern NumPy. It provides better statistical properties, performance, and a more flexible way to manage the random state compared to the older module-level functions.

**`np.random.default_rng(seed=None)`:** This function returns a new `Generator` object.

**Chain of Thought:**
1. The user should be introduced to the modern way of generating random numbers in NumPy.
2. This involves creating a `Generator` object using `np.random.default_rng()`.
3. The `seed` argument can be provided to the `default_rng()` function to ensure reproducibility, similar to `np.random.seed()`.

**Example 37:** Create a `Generator` object without a seed.
**Example 38:** Create a `Generator` object with a seed for reproducibility.

In [22]:
# Example 36: Save and restore the random state
print("\nExample 36: Saving and restoring random state")

# Generate some random numbers and save the state
np.random.seed(42)
print("Initial random numbers:", np.random.rand(3))
saved_state = np.random.get_state()
print("Random numbers after saving state:", np.random.rand(3))

# Restore the state and generate random numbers again
np.random.set_state(saved_state)
print("Random numbers after restoring state (should be the same as after saving):", np.random.rand(3))


Example 36: Saving and restoring random state
Initial random numbers: [0.37454012 0.95071431 0.73199394]
Random numbers after saving state: [0.59865848 0.15601864 0.15599452]
Random numbers after restoring state (should be the same as after saving): [0.59865848 0.15601864 0.15599452]


**`np.random.get_state()` and `np.random.set_state(state)`:** Get or set the internal state of the random number generator. Useful for saving and restoring the state to reproduce a sequence of random numbers exactly, even across different runs or sessions.

**Chain of Thought:**
1. The user might want to save the exact state of the random generator at a point in time.
2. This allows resuming the random sequence later or in a different environment.
3. `np.random.get_state()` retrieves the current state.
4. `np.random.set_state()` restores the state.

**Example 36:** Save and restore the random state.

In [21]:
# Example 35: Generate a string of 10 random bytes
print("\nExample 35: 10 random bytes:", np.random.bytes(10))


Example 35: 10 random bytes: b'y"\x8a\xb3"p\xcbN\xd1\xa4'


**5. Other Utility Functions and Attributes**

The `np.random` module also includes other functions and attributes.

**`np.random.bytes(length)`:** Return random bytes.

**Chain of Thought:**
1. The user might need random bytes for various purposes (e.g., cryptography, unique identifiers).
2. `np.random.bytes()` generates a string of random bytes.

**Example 35:** Generate a string of 10 random bytes.

In [20]:
# Example 32: Get a random permutation of an integer range
print("\nExample 32: Random permutation of range 10:", np.random.permutation(10))

# Example 33: Get a random permutation of a 1D array
arr_1d = np.arange(10)
print("\nExample 33: Original 1D array:", arr_1d)
permuted_arr_1d = np.random.permutation(arr_1d)
print("Permuted 1D array (new):", permuted_arr_1d)
print("Original 1D array after permutation:", arr_1d) # Original is unchanged

# Example 34: Get a random permutation of rows in a 2D array
arr_2d = np.arange(12).reshape(4, 3)
print("\nExample 34: Original 2D array:\n", arr_2d)
permuted_arr_2d = np.random.permutation(arr_2d) # Permutes rows
print("Permuted 2D array (rows permuted, new):\n", permuted_arr_2d)
print("Original 2D array after permutation:\n", arr_2d) # Original is unchanged


Example 32: Random permutation of range 10: [6 9 4 5 2 7 1 3 0 8]

Example 33: Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Permuted 1D array (new): [1 8 6 2 7 0 3 9 4 5]
Original 1D array after permutation: [0 1 2 3 4 5 6 7 8 9]

Example 34: Original 2D array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Permuted 2D array (rows permuted, new):
 [[ 6  7  8]
 [ 9 10 11]
 [ 3  4  5]
 [ 0  1  2]]
Original 2D array after permutation:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


**`np.random.permutation(x)`:** Randomly permute a sequence, or return a permuted range.

**Chain of Thought:**
1. The user wants a random reordering of an array's elements or a range.
2. The reordering should produce a new array, leaving the original unchanged.
3. `np.random.permutation()` is used for this.
4. If `x` is an integer, it returns a permuted `np.arange(x)`. If `x` is an array, it returns a copy with rows (for 2D and higher) or elements (for 1D) permuted.

**Example 32:** Get a random permutation of an integer range.
**Example 33:** Get a random permutation of a 1D array.
**Example 34:** Get a random permutation of rows in a 2D array.

In [169]:
# Example 30: Shuffle a 1D array in-place
arr_1d = np.arange(10)
print("\nExample 30: Original 1D array:", arr_1d)
np.random.shuffle(arr_1d)
print("Shuffled 1D array (in-place):", arr_1d)

# Example 31: Shuffle rows of a 2D array in-place
arr_2d = np.arange(12).reshape(4, 3)
print("\nExample 31: Original 2D array:\n", arr_2d)
np.random.shuffle(arr_2d) # Shuffles rows
print("Shuffled 2D array (rows shuffled in-place):\n", arr_2d)


Example 30: Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Shuffled 1D array (in-place): [4 7 8 1 0 3 2 5 9 6]

Example 31: Original 2D array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shuffled 2D array (rows shuffled in-place):
 [[ 3  4  5]
 [ 9 10 11]
 [ 6  7  8]
 [ 0  1  2]]


**4. Functions for Permutations and Shuffling**

These functions are used to randomly reorder elements in arrays.

**`np.random.shuffle(x)`:** Modify a sequence in-place by shuffling its contents. This only shuffles along the first axis of a multi-dimensional array.

**Chain of Thought:**
1. The user wants to randomly reorder the elements of an array.
2. The reordering should happen directly on the original array.
3. `np.random.shuffle()` is used for this.

**Example 30:** Shuffle a 1D array in-place.
**Example 31:** Shuffle rows of a 2D array in-place.

In [170]:
# Example 28: Generate samples from a Geometric distribution (p=0.4)
print("\nExample 28: Samples from Geometric distribution (p=0.4):\n", np.random.geometric(0.4, size=5))

# Example 29: Generate samples from a Hypergeometric distribution
# Drawing 10 marbles from a bag with 10 good and 15 bad marbles
print("\nExample 29: Samples from Hypergeometric distribution (ngood=10, nbad=15, nsample=10):\n", np.random.hypergeometric(10, 15, 10, size=5))


Example 28: Samples from Geometric distribution (p=0.4):
 [1 2 3 3 3]

Example 29: Samples from Hypergeometric distribution (ngood=10, nbad=15, nsample=10):
 [6 3 3 5 3]


**Other Discrete Distributions:** The `np.random` module includes functions for other discrete distributions, such as:
- `geometric(p, size=None)`: Geometric distribution
- `hypergeometric(ngood, nbad, nsample, size=None)`: Hypergeometric distribution
- `logseries(p, size=None)`: Logarithmic Series distribution
- `negative_binomial(n, p, size=None)`: Negative Binomial distribution
- `zipf(a, size=None)`: Zipf distribution

Let's show a couple more examples.

**Example 28:** Generate samples from a Geometric distribution.
**Example 29:** Generate samples from a Hypergeometric distribution.

In [17]:
# Example 26: Simulate a single event count with an average rate of 3
print("\nExample 26: Poisson(lam=3) single event:", np.random.poisson(3))

# Example 27: Simulate event counts with an average rate of 5, repeated 6 times
print("\nExample 27: Poisson(lam=5) 6 events:\n", np.random.poisson(5, size=6))


Example 26: Poisson(lam=3) single event: 0

Example 27: Poisson(lam=5) 6 events:
 [ 3 11  7  7  3  6]


**`np.random.poisson(lam=1.0, size=None)`:** Draw samples from a Poisson distribution.

**Chain of Thought:**
1. The user wants to simulate the number of events occurring in a fixed interval of time or space, given an average rate.
2. `np.random.poisson()` is used for this.
3. `lam` (lambda) is the expected number of events in the interval.
4. `size` specifies the output shape.

**Example 26:** Simulate a single event count with an average rate of 3.
**Example 27:** Simulate event counts with an average rate of 5, repeated 6 times.

In [16]:
# Example 24: Simulate 10 trials with a 50% success rate once
print("\nExample 24: Binomial(n=10, p=0.5) single trial:", np.random.binomial(10, 0.5))

# Example 25: Simulate 10 trials with a 30% success rate, repeated 5 times
print("\nExample 25: Binomial(n=10, p=0.3) 5 trials:\n", np.random.binomial(10, 0.3, size=5))


Example 24: Binomial(n=10, p=0.5) single trial: 5

Example 25: Binomial(n=10, p=0.3) 5 trials:
 [3 4 1 4 3]


**`np.random.binomial(n, p, size=None)`:** Draw samples from a binomial distribution.

**Chain of Thought:**
1. The user wants to simulate the number of successes in a series of independent Bernoulli trials.
2. `np.random.binomial()` is used for this.
3. `n` is the number of trials, and `p` is the probability of success in each trial.
4. `size` specifies the output shape.

**Example 24:** Simulate 10 trials with a 50% success rate once.
**Example 25:** Simulate 10 trials with a 30% success rate, repeated 5 times.

In [15]:
# Example 19: Randomly pick a single element from an array
elements = [1, 2, 3, 4, 5]
print("\nExample 19: Randomly pick a single element:", np.random.choice(elements))

# Example 20: Randomly pick 5 elements with replacement from an array
print("\nExample 20: Randomly pick 5 elements with replacement:\n", np.random.choice(elements, size=5, replace=True))

# Example 21: Randomly pick 3 elements without replacement from an array
print("\nExample 21: Randomly pick 3 elements without replacement:\n", np.random.choice(elements, size=3, replace=False))

# Example 22: Randomly pick elements with specified probabilities
# Elements [1, 2, 3, 4, 5] with probabilities [0.1, 0.2, 0.3, 0.2, 0.2]
probabilities = [0.1, 0.2, 0.3, 0.2, 0.2]
print("\nExample 22: Randomly pick elements with probabilities:\n", np.random.choice(elements, size=10, p=probabilities))

# Example 23: Randomly pick from an integer range (equivalent to np.random.randint)
print("\nExample 23: Randomly pick from integer range [0, 10) (size 5):\n", np.random.choice(10, size=5))


Example 19: Randomly pick a single element: 3

Example 20: Randomly pick 5 elements with replacement:
 [5 4 5 5 3]

Example 21: Randomly pick 3 elements without replacement:
 [4 3 5]

Example 22: Randomly pick elements with probabilities:
 [3 2 3 3 5 2 2 5 1 4]

Example 23: Randomly pick from integer range [0, 10) (size 5):
 [2 3 6 4 1]


**`np.random.choice(a, size=None, replace=True, p=None)`:** Generates a random sample from a given 1-D array (`a`) or from an integer range.

**Chain of Thought:**
1. The user wants to randomly select elements from an existing array or a range.
2. `np.random.choice()` is the function for this.
3. `a` is the array or integer range to sample from.
4. `size` is the number of samples to draw.
5. `replace=True` (default) means sampling with replacement (an element can be chosen multiple times), `replace=False` means sampling without replacement.
6. `p` allows specifying the probabilities of each element in `a` being chosen.

**Example 19:** Randomly pick a single element from an array.
**Example 20:** Randomly pick 5 elements with replacement from an array.
**Example 21:** Randomly pick 3 elements without replacement from an array.
**Example 22:** Randomly pick elements with specified probabilities.
**Example 23:** Randomly pick from an integer range (equivalent to `np.random.randint`).

In [14]:
# Example 16: Generate a single random integer between 0 and 10 (exclusive of 10)
print("\nExample 16: Single random integer [0, 10):", np.random.randint(10))

# Example 17: Generate a 1D array of random integers between 1 and 7 (exclusive of 7)
print("\nExample 17: 1D array of random integers [1, 7):\n", np.random.randint(1, 7, size=8))

# Example 18: Generate a 2x4 array of random integers between 50 and 100 (exclusive of 100)
print("\nExample 18: 2x4 array of random integers [50, 100):\n", np.random.randint(50, 100, size=(2, 4)))


Example 16: Single random integer [0, 10): 4

Example 17: 1D array of random integers [1, 7):
 [3 4 4 2 3 4 1 2]

Example 18: 2x4 array of random integers [50, 100):
 [[95 87 75 95]
 [85 66 62 72]]


**3. Functions for Discrete Distributions**

These functions generate random integers or samples from discrete probability distributions.

**`np.random.randint(low, high=None, size=None, dtype='int_')`:** Return random integers from `low` (inclusive) to `high` (exclusive).

**Chain of Thought:**
1. The user wants random integers within a specified range.
2. `np.random.randint()` is the function for this.
3. `low` is the lower bound (inclusive), and `high` is the upper bound (exclusive).
4. `size` specifies the output shape.

**Example 16:** Generate a single random integer between 0 and 10 (exclusive of 10).
**Example 17:** Generate a 1D array of random integers between 1 and 7 (exclusive of 7).
**Example 18:** Generate a 2x4 array of random integers between 50 and 100 (exclusive of 100).

In [154]:
import numpy as np

# Example 13: Generate samples from a Beta distribution
print("\nExample 13: Samples from Beta distribution (a=2, b=3):\n", np.random.beta(2, 3, size=5))


Example 13: Samples from Beta distribution (a=2, b=3):
 [0.08909167 0.27596558 0.45252523 0.40086153 0.62314346]


In [13]:
# Example 14: Generate samples from a Beta distribution
print("\nExample 14: Samples from Beta distribution (a=0.5, b=0.5):\n", np.random.beta(0.5, 0.5, size=5))

# Example 15: Generate samples from a Logistic distribution
print("\nExample 15: Samples from Logistic distribution (loc=0, scale=1):\n", np.random.logistic(size=5))


Example 14: Samples from Beta distribution (a=0.5, b=0.5):
 [0.28716118 0.95125426 0.70696615 0.75955092 0.55757422]

Example 15: Samples from Logistic distribution (loc=0, scale=1):
 [-1.56026934  3.36552919  3.10290952  0.3970292   1.00123209]


In [168]:
# beta(a, b, size):
# a and b: These are the shape parameters of the Beta distribution. They influence the shape of the distribution.
# exponential(scale=1.0, size=None):
import numpy as np
a=np.random.beta(2, 3, size=(2,3))
e=np.random.exponential(scale=1.0, size=(2,3))
print(e)
print(a)
# scale: This is the scale parameter of the Exponential distribution. It's the inverse of the rate parameter (λ).
# gamma(shape, scale=1.0, size=None):
g=np.random.gamma(2, scale=1.0, size=(2,3))
print('gamma value is ',g)
# shape: This is the shape parameter (k) of the Gamma distribution.
# scale: This is the scale parameter (θ) of the Gamma distribution.
# logistic(loc=0.0, scale=1.0, size=None):
l=np.random.logistic(loc=0.0, scale=1.0, size=(2,3))
print('logistic value is ',l)
# loc: This is the location parameter (μ) of the Logistic distribution, which is also its mean.
# scale: This is the scale parameter (s) of the Logistic distribution.
# power(a, size=None):
p=np.random.power(2, size=(2,3))
print('power value is ',p)
# a: This is the exponent parameter of the Power distribution.
# rayleigh(scale=1.0, size=None):
# scale: This is the scale parameter (σ) of the Rayleigh distribution.
# standard_cauchy(size=None):
sc=
# This is the standard Cauchy distribution, which is a special case of the Cauchy distribution with a location of 0 and a scale of 1. It doesn't have specific parameters you typically pass beyond the size.
# standard_gamma(shape, size=None):
# shape: This is the shape parameter (k) of the standard Gamma distribution. The scale is fixed at 1.0.
# standard_t(df, size=None):
# df: This is the degrees of freedom parameter (ν) of the standard Student's t distribution.
# triangular(left, mode, right, size=None):
# left: The lower limit of the distribution.
# mode: The peak of the distribution.
# right: The upper limit of the distribution.
# vonmises(mu, kappa, size=None):
# mu: This is the mean angle (μ) of the Von Mises distribution.
# kappa: This is the concentration parameter (κ) of the Von Mises distribution.
# wald(mean, scale, size=None):
# mean: This is the mean (μ) of the Wald (Inverse Gaussian) distribution.
# scale: This is the scale parameter (λ) of the Wald distribution.
# weibull(a, size=None):
# a: This is the shape parameter (k) of the Weibull distribution.
# These parameters define the specific characteristics (shape, location, scale, etc.) of the random numbers generated from each distribution.


# er Continuous Distributions: The np.random module includes functions for many other continuous distributions, such as: beta(a, b, size): Beta distribution exponential(scale=1.0, size=None): Exponential distribution gamma(shape, scale=1.0, size=None): Gamma distribution logistic(loc=0.0, scale=1.0, size=None): Logistic distribution power(a, size=None): Power distribution rayleigh(scale=1.0, size=None): Rayleigh distribution standard_cauchy(size=None): Standard Cauchy distribution standard_gamma(shape, size=None): Standard Gamma distribution standard_t(df, size=None): Standard Student's t distribution triangular(left, mode, right, size=None): Triangular distribution vonmises(mu, kappa, size=None): Von Mises distribution wald(mean, scale, size=None): Wald (Inverse Gaussian) distribution weibull(a, size=None): Weibull distribution Let's show a couple more examples.

# You stopped this response

# explain a and b
# Based on our previous conversation about probability distributions in numpy.random, it seems you are asking about the a and b parameters for the Beta distribution.

# In the context of the Beta distribution:

# a (alpha): This is the first shape parameter. It is also sometimes referred to as the "pseudo-count of successes" or similar interpretations depending on the context (e.g., in Bayesian statistics). A larger a value shifts the distribution towards higher values.
# b (beta): This is the second shape parameter. It is sometimes referred to as the "pseudo-count of failures". A larger b value shifts the distribution towards lower values.

SyntaxError: invalid syntax (ipython-input-348782466.py, line 27)

**Other Continuous Distributions:** The `np.random` module includes functions for many other continuous distributions, such as:
- `beta(a, b, size)`: Beta distribution
- `exponential(scale=1.0, size=None)`: Exponential distribution
- `gamma(shape, scale=1.0, size=None)`: Gamma distribution
- `logistic(loc=0.0, scale=1.0, size=None)`: Logistic distribution
- `power(a, size=None)`: Power distribution
- `rayleigh(scale=1.0, size=None)`: Rayleigh distribution
- `standard_cauchy(size=None)`: Standard Cauchy distribution
- `standard_gamma(shape, size=None)`: Standard Gamma distribution
- `standard_t(df, size=None)`: Standard Student's t distribution
- `triangular(left, mode, right, size=None)`: Triangular distribution
- `vonmises(mu, kappa, size=None)`: Von Mises distribution
- `wald(mean, scale, size=None)`: Wald (Inverse Gaussian) distribution
- `weibull(a, size=None)`: Weibull distribution

Let's show a couple more examples.

**Example 14:** Generate samples from a Beta distribution.
**Example 15:** Generate samples from a Logistic distribution.

In [12]:
# Example 11: Generate a single normal random number with default parameters
print("\nExample 11: Single normal random number (mean=0, std=1):", np.random.normal())

# Example 12: Generate a 1D array from a normal distribution with mean 10 and std dev 2
print("\nExample 12: 1D array from normal (mean=10, std=2):\n", np.random.normal(loc=10, scale=2, size=7))

# Example 13: Generate a 3x3 array from a normal distribution with mean -5 and std dev 0.5
print("\nExample 13: 3x3 array from normal (mean=-5, std=0.5):\n", np.random.normal(loc=-5, scale=0.5, size=(3, 3)))


Example 11: Single normal random number (mean=0, std=1): -0.6543810337119073

Example 12: 1D array from normal (mean=10, std=2):
 [ 9.34752388 10.11135203 10.44479922  7.11356601  8.48729539 11.63290802
 11.50088952]

Example 13: 3x3 array from normal (mean=-5, std=0.5):
 [[-5.22797346 -4.40518887 -5.84530841]
 [-5.67819952 -5.61621726 -5.27221958]
 [-5.33408587 -4.99634272 -5.30646937]]


**`np.random.normal(loc=0.0, scale=1.0, size=None)`:** Draw random samples from a normal (Gaussian) distribution.

**Chain of Thought:**
1. The user wants random numbers from a normal distribution with specific mean and standard deviation.
2. `np.random.normal()` is the function for this.
3. `loc` is the mean and `scale` is the standard deviation.
4. `size` specifies the output shape.

**Example 11:** Generate a single normal random number with default parameters.
**Example 12:** Generate a 1D array from a normal distribution with mean 10 and std dev 2.
**Example 13:** Generate a 3x3 array from a normal distribution with mean -5 and std dev 0.5.

In [11]:
# Example 8: Generate a single uniform random float between 5 and 10
print("\nExample 8: Single uniform random float [5, 10):", np.random.uniform(5, 10))

# Example 9: Generate a 1D array of uniform random floats between -1 and 1
print("\nExample 9: 1D array of uniform random floats [-1, 1):\n", np.random.uniform(-1, 1, size=6))

# Example 10: Generate a 2x3 array of uniform random floats between 100 and 200
print("\nExample 10: 2x3 array of uniform random floats [100, 200):\n", np.random.uniform(100, 200, size=(2, 3)))


Example 8: Single uniform random float [5, 10): 5.076274856231695

Example 9: 1D array of uniform random floats [-1, 1):
 [ 0.19768675  0.20760908 -0.78970463 -0.23611311 -0.92704789  0.78082313]

Example 10: 2x3 array of uniform random floats [100, 200):
 [[198.0920857  105.99419888 189.05459447]
 [157.69014994 174.24796891 163.01839365]]


**`np.random.uniform(low=0.0, high=1.0, size=None)`:** Draw samples from a uniform distribution over the interval `[low, high)`.

**Chain of Thought:**
1. The user wants uniform random numbers within a specific range other than [0, 1).
2. `np.random.uniform()` allows specifying the lower (`low`) and upper (`high`) bounds.
3. The `size` argument specifies the output shape.

**Example 8:** Generate a single uniform random float between 5 and 10.
**Example 9:** Generate a 1D array of uniform random floats between -1 and 1.
**Example 10:** Generate a 2x3 array of uniform random floats between 100 and 200.

In [10]:
# Example 5: Generate a single random number from standard normal
print("\nExample 5: Single standard normal random number:", np.random.randn())

# Example 6: Generate a 1D array from standard normal
print("\nExample 6: 1D array from standard normal:\n", np.random.randn(4))

# Example 7: Generate a 3x2 array from standard normal
print("\nExample 7: 3x2 array from standard normal:\n", np.random.randn(3, 2))


Example 5: Single standard normal random number: -0.5771615049059661

Example 6: 1D array from standard normal:
 [-0.53337271 -0.22540212 -0.31491934  0.42299678]

Example 7: 3x2 array from standard normal:
 [[-0.43882681 -0.50141346]
 [-1.65870284 -1.0075773 ]
 [-0.50873443  0.78148842]]


**`np.random.randn(d0, d1, ..., dn)`:** Return a sample (or samples) from the "standard normal" distribution.

**Chain of Thought:**
1. The user wants random numbers from a standard normal distribution (mean=0, variance=1).
2. `np.random.randn()` is the function for this.
3. The arguments specify the dimensions of the output array.

**Example 5:** Generate a single random number from standard normal.
**Example 6:** Generate a 1D array from standard normal.
**Example 7:** Generate a 3x2 array from standard normal.

In [153]:
# Example 2: Generate a single random float
print("\nExample 2: Single uniform random float:", np.random.rand())

# Example 3: Generate a 1D array of uniform random floats
print("\nExample 3: 1D array of uniform random floats:\n", np.random.rand(5))

# Example 4: Generate a 2x2 array of uniform random floats
print("\nExample 4: 2x2 array of uniform random floats:\n", np.random.rand(2, 2))


Example 2: Single uniform random float: 0.08074126876487486

Example 3: 1D array of uniform random floats:
 [0.7384403  0.44130922 0.15830987 0.87993703 0.27408646]

Example 4: 2x2 array of uniform random floats:
 [[0.41423502 0.29607993]
 [0.62878791 0.57983781]]


**2. Functions for Continuous Distributions**

These functions generate random numbers from continuous probability distributions.

**`np.random.rand(d0, d1, ..., dn)`:** Create an array of the given shape and populate it with random samples from a uniform distribution over `[0, 1)`.

**Chain of Thought:**
1. The user wants uniform random numbers between 0 and 1.
2. `np.random.rand()` is the function for this.
3. The arguments specify the dimensions of the output array.

**Example 2:** Generate a single random float.
**Example 3:** Generate a 1D array of uniform random floats.
**Example 4:** Generate a 2x2 array of uniform random floats.

In [152]:
# Example 1: Basic usage of np.random.seed()
import numpy as np

# np.random.seed(42)
# print("Seed 42, first random number:", np.random.rand())

# np.random.seed(42) # Resetting the seed
# print("Seed 42, second random number (should be the same):", np.random.rand())

# np.random.seed(100) # Different seed
# print("Seed 100, first random number:", np.random.rand())
np.random.seed(5)
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())

0.22199317108973948
0.8707323061773764
0.20671915533942642
0.9186109079379216
0.48841118879482914
0.6117438629026457
0.7659078564803156
0.5184179878729432
0.29680050157622195
0.18772122866125163


**Step 2: Cover Older Module-level Functions**

These functions operate on a global random state. While convenient for simple use cases, managing reproducibility can be less flexible compared to the `Generator` class.

**1. Setting the Seed (`np.random.seed`)**

**Chain of Thought:**
1. To make random number generation reproducible, we need to set a starting point for the algorithm.
2. `np.random.seed()` is used for this in the older approach.
3. Providing the same integer seed will result in the same sequence of "random" numbers.

**Example 1:** Basic usage of `np.random.seed()`.

**Step 1: Introduce `np.random` Module**

The `numpy.random` module is a crucial part of NumPy for generating pseudorandom numbers. These numbers are not truly random but are generated by deterministic algorithms based on a seed. The module provides a wide range of functions for generating random numbers from various probability distributions, as well as tools for shuffling and sampling.

Historically, NumPy's random number generation was primarily done through module-level functions (like `np.random.rand()`, `np.random.randint()`, etc.). While still available, the recommended modern approach is to use a `Generator` object created by `np.random.default_rng()`. This newer approach offers better statistical properties, performance, and control over the random number generation process.

We will cover both approaches, starting with the older module-level functions for completeness and then moving on to the `Generator` class.